# Source reship list
VPATH = ..
ILIST = \
  atrig_test.cpp \
  Makefile.ode
atrig_test.cpp_IDIR = $(BG_SRC)/BlueMatter/util/test/
Makefile.ode_IDIR = $(BG_SRC)/BlueMatter/util/test/source_ship/
.include <$(RULES_MK)>
