OBJECTS_SUBDIRS = smp
.if $(CAN_BUILD_MPI) != 0
OBJECTS_SUBDIRS += mpi
.endif

EXPLIB_SUBDIRS = $(OBJECTS_SUBDIRS)
SUBDIRS = $(OBJECTS_SUBDIRS)

.if defined(RESHIP_SOURCE)
ILIST += Makefile.ode
Makefile.ode_IDIR = $(BG_SRC)/./bgfe/pk/util_comm/src/
INSTALL_STANDARD_SUBDIRS = $(SUBDIRS) $(STANDARD_SUBDIRS) source_ship
.endif # RESHIP_SOURCE
.include <$(RULES_MK)>
