# Source reship list
VPATH = ..
ILIST = \
  fxlogger.cpp \
  logdiff \
  logdiff.cpp \
  makefile.aix \
  Makefile.ode
fxlogger.cpp_IDIR = $(BG_SRC)/bgfe/pk/fxlogger/src/
logdiff_IDIR = $(BG_SRC)/bgfe/pk/fxlogger/src/
logdiff.cpp_IDIR = $(BG_SRC)/bgfe/pk/fxlogger/src/
makefile.aix_IDIR = $(BG_SRC)/bgfe/pk/fxlogger/src/
Makefile.ode_IDIR = $(BG_SRC)/bgfe/pk/fxlogger/src/source_ship/
.include <$(RULES_MK)>
