OFILES  = \
	treebroadcast$(OBJ_SUFF) \

CFLAGS += $(SMPCFLAGS)
OBJECTS = $(OFILES)
.if defined(RESHIP_SOURCE)
ILIST += Makefile.ode
Makefile.ode_IDIR = $(BG_SRC)/./bgfe/pk/blimpi/treeboadcast/src/
INSTALL_STANDARD_SUBDIRS = $(SUBDIRS) $(STANDARD_SUBDIRS) source_ship
.endif # RESHIP_SOURCE
.include <$(RULES_MK)>
