CFLAGS  += -D EWALD $(SMPCFLAGS)
LIBS    =       $(PKSMPLIBS)

VPATH   = ../..

OFILES         = \
  ewaldsmpp1$(OBJ_SUFF)

PROGRAMS        = \
  p1$(PROG_SUFF)

IDIR                = $(BG_BIN)/kernels/smp/ewald/

ILIST   =       $(PROGRAMS)

.if defined(RESHIP_SOURCE)
ILIST += Makefile.ode
Makefile.ode_IDIR = $(BG_SRC)/./BlueMatter/kerngen/smp/ewald/
.endif # RESHIP_SOURCE
.include <$(RULES_MK)>
