# Source reship list
VPATH = ..
ILIST = \
  build_all.sh \
  build_component.sh \
  Makefile.ode
build_all.sh_IDIR = $(BG_SRC)/BlueMatter/probspecdb2/
build_component.sh_IDIR = $(BG_SRC)/BlueMatter/probspecdb2/
Makefile.ode_IDIR = $(BG_SRC)/BlueMatter/probspecdb2/source_ship/
.include <$(RULES_MK)>
