# Source reship list
VPATH = ..
ILIST = \
  MSDIF.cpp \
  MSD_IF.cpp \
  Makefile.ode
MSDIF.cpp_IDIR = $(BG_SRC)/BlueMatter/molsysdef/src/
MSD_IF.cpp_IDIR = $(BG_SRC)/BlueMatter/molsysdef/src/
Makefile.ode_IDIR = $(BG_SRC)/BlueMatter/molsysdef/src/source_ship/
.include <$(RULES_MK)>
