OBJECTS = fftmain$(OBJ_SUFF) \

INCLUDES = fft_one_dim.hpp \
	PacketCounterManager.hpp \
	fft3D.hpp \

EXPINCDIR = /usr/include/BlueMatter/ 

BG_OPT_LEVEL = 3
BG_TRUST_LEVEL = 0

#-DUSE_2_CORES_FOR_FFT
#-qsource -qlist -qshowinc
CFLAGS += $(SMPCFLAGS) -DUSE_2_CORES_FOR_FFT -DRDG_TO_FXLOGGER  -DPK_BGL -DPK_BLADE -DPKFXLOG -DPKFXLOG_ALL -qsource -qlist -qshowinc

.include <$(RULES_MK)>
