EXPINC_SUBDIRS = \
  traceutils \

OBJECTS_SUBDIRS = \
  $(EXPINC_SUBDIRS) \
  
CMFPARSE_SUBDIRS = packaging

SUBDIRS = \
  $(EXPINC_SUBDIRS) \
  $(CMFPARSE_SUBDIRS) \

.if defined(RESHIP_SOURCE)
ILIST += Makefile.ode
Makefile.ode_IDIR = $(BG_SRC)/./pktools/
INSTALL_STANDARD_SUBDIRS = $(SUBDIRS) $(STANDARD_SUBDIRS) source_ship
.endif # RESHIP_SOURCE
.include <$(RULES_MK)>

