# Source reship list
VPATH = ..
ILIST = \
  enkp.out \
  enkp.pdb \
  enkp.prm \
  enkp.xml \
  oplsprm.inp \
  Makefile.ode
enkp.out_IDIR = $(BG_SRC)/BlueMatter/xmlgen/oplsaa/example/
enkp.pdb_IDIR = $(BG_SRC)/BlueMatter/xmlgen/oplsaa/example/
enkp.prm_IDIR = $(BG_SRC)/BlueMatter/xmlgen/oplsaa/example/
enkp.xml_IDIR = $(BG_SRC)/BlueMatter/xmlgen/oplsaa/example/
oplsprm.inp_IDIR = $(BG_SRC)/BlueMatter/xmlgen/oplsaa/example/
Makefile.ode_IDIR = $(BG_SRC)/BlueMatter/xmlgen/oplsaa/example/source_ship/
.include <$(RULES_MK)>
