# Source reship list
VPATH = ..
ILIST = \
  baixsmp \
  redapp.cpp \
  Makefile.ode
baixsmp_IDIR = $(BG_SRC)/bgfe/pk/collective/test/
redapp.cpp_IDIR = $(BG_SRC)/bgfe/pk/collective/test/
Makefile.ode_IDIR = $(BG_SRC)/bgfe/pk/collective/test/source_ship/
.include <$(RULES_MK)>
