VPATH = ..

OFILES  = \
	smp_reactor$(OBJ_SUFF) \

OBJECTS = $(OFILES)

LIBRARIES = $(LIB_PREF)pksmp_reactor$(LIB_SUFF)

EXPLIBS = $(LIBRARIES)
EXPLIBDIR = /usr/lib/

ILIST = $(LIBRARIES) \

IDIR = $(BG_LIB)/

CFLAGS += $(SMPCFLAGS)

.if defined(RESHIP_SOURCE)
ILIST += Makefile.ode
Makefile.ode_IDIR = $(BG_SRC)/./bgfe/pk/reactor/src/smp/
.endif # RESHIP_SOURCE
.include <$(RULES_MK)>
