BG_AUXILIARY = 1


EXPINC_SUBDIRS = \
 include \

EXPLIB_SUBDIRS = \
 src \

OBJECTS_SUBDIRS = \
 src 


SUBDIRS = \
     $(EXPINC_SUBDIRS) \
     $(OBJECTS_SUBDIRS) \


#IDIR = $(BG_BIN)/setup/
IDIR = $(BG_BIN)/

.include <$(RULES_MK)>

.if defined(RESHIP_SOURCE)
ILIST += Makefile.ode
Makefile.ode_IDIR = $(BG_SRC)/./BlueMatter/concept_dbalg/
INSTALL_STANDARD_SUBDIRS = $(SUBDIRS) $(STANDARD_SUBDIRS) source_ship
.endif # RESHIP_SOURCE

.include <$(RULES_MK)>
