# Source reship list
VPATH = ..
ILIST = \
  McEnergy.cpp \
  dvsconv.cpp \
  Makefile.ode
McEnergy.cpp_IDIR = $(BG_SRC)/BlueMatter/util/rdg/
dvsconv.cpp_IDIR = $(BG_SRC)/BlueMatter/util/rdg/
Makefile.ode_IDIR = $(BG_SRC)/BlueMatter/util/rdg/source_ship/
.include <$(RULES_MK)>
