

EXPINC_SUBDIRS = \
 fft3d \
 pk \
 PhasedPipeline \
 packaging \

OBJECTS_SUBDIRS = $(EXPINC_SUBDIRS)
EXPLIB_SUBDIRS = $(EXPINC_SUBDIRS)
SUBDIRS = $(EXPINC_SUBDIRS)

CMFPARSE_SUBDIRS = packaging

RUNPKGTOOL_SUBDIRS = $(CMFPARSE_SUBDIRS)

ILIST += bgfe.version

bgfe.version_IDIR = $(BG_DIR)/

.if defined(RESHIP_SOURCE)
ILIST += Makefile.ode
Makefile.ode_IDIR = $(BG_SRC)/./bgfe/
INSTALL_STANDARD_SUBDIRS = $(SUBDIRS) $(STANDARD_SUBDIRS) source_ship
.endif # RESHIP_SOURCE
.include <$(RULES_MK)>
