-- This CLP file was created using DB2LOOK Version 8.2
-- Timestamp: Thu May 18 03:20:20 EDT 2006
-- Database Name: MDSETUP        
-- Database Manager Version: DB2/6000 Version 8.2.4        
-- Database Codepage: 819
-- Database Collating Sequence is: UNIQUE


CONNECT TO MDSETUP;



------------------------------------------------
-- DDL Statements for table "PERF    "."TRACE_GROUP"
------------------------------------------------
 
 CREATE TABLE "PERF    "."TRACE_GROUP"  (
		  "GROUP_ID" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY (  
		    START WITH +1  
		    INCREMENT BY +1  
		    MINVALUE +1  
		    MAXVALUE +2147483647  
		    NO CYCLE  
		    CACHE 20  
		    NO ORDER ) , 
		  "CREATOR" VARCHAR(30) NOT NULL , 
		  "CREATED" TIMESTAMP NOT NULL , 
		  "DESC" VARCHAR(1024) )   
		 IN "MDSHORT" ; 

-- DDL Statements for primary key on Table "PERF    "."TRACE_GROUP"

ALTER TABLE "PERF    "."TRACE_GROUP" 
	ADD PRIMARY KEY
		("GROUP_ID");



------------------------------------------------
-- DDL Statements for table "PERF    "."TRACE_SET"
------------------------------------------------
 
 CREATE TABLE "PERF    "."TRACE_SET"  (
		  "TRACE_SET_ID" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY (  
		    START WITH +1  
		    INCREMENT BY +1  
		    MINVALUE +1  
		    MAXVALUE +2147483647  
		    NO CYCLE  
		    CACHE 20  
		    NO ORDER ) , 
		  "GROUP_ID" INTEGER NOT NULL , 
		  "EXECUTABLE_ID" INTEGER NOT NULL , 
		  "NODE_COUNT" INTEGER NOT NULL , 
		  "BIN_FILE" VARCHAR(128) NOT NULL )   
		 IN "MDSHORT" ; 

-- DDL Statements for primary key on Table "PERF    "."TRACE_SET"

ALTER TABLE "PERF    "."TRACE_SET" 
	ADD PRIMARY KEY
		("TRACE_SET_ID");



------------------------------------------------
-- DDL Statements for table "PERF    "."TRACE_SET_DATA"
------------------------------------------------
 
 CREATE TABLE "PERF    "."TRACE_SET_DATA"  (
		  "TRACE_SET_ID" INTEGER NOT NULL , 
		  "NAME" VARCHAR(64) NOT NULL , 
		  "VALUE" VARCHAR(256) NOT NULL )   
		 IN "MDSHORT" ; 

-- DDL Statements for primary key on Table "PERF    "."TRACE_SET_DATA"

ALTER TABLE "PERF    "."TRACE_SET_DATA" 
	ADD PRIMARY KEY
		("TRACE_SET_ID",
		 "NAME");



------------------------------------------------
-- DDL Statements for table "PERF    "."TRACE_ID"
------------------------------------------------
 
 CREATE TABLE "PERF    "."TRACE_ID"  (
		  "TRACE_SET_ID" INTEGER NOT NULL , 
		  "TRACE_ID" INTEGER NOT NULL , 
		  "TRACE_TYPE" INTEGER NOT NULL , 
		  "TRACE_LABEL" VARCHAR(48) NOT NULL , 
		  "TRACE_DESC" VARCHAR(256) NOT NULL )   
		 IN "MDSHORT" ; 

-- DDL Statements for primary key on Table "PERF    "."TRACE_ID"

ALTER TABLE "PERF    "."TRACE_ID" 
	ADD PRIMARY KEY
		("TRACE_SET_ID",
		 "TRACE_ID");



------------------------------------------------
-- DDL Statements for table "PERF    "."PERFORMANCE"
------------------------------------------------
 
 CREATE TABLE "PERF    "."PERFORMANCE"  (
		  "TRACE_SET_ID" INTEGER NOT NULL , 
		  "TRACE_LABEL" VARCHAR(48) NOT NULL , 
		  "AVG" DOUBLE , 
		  "STD_DEV" DOUBLE , 
		  "MIN" DOUBLE , 
		  "MAX" DOUBLE , 
		  "COUNT" INTEGER , 
		  "MIN_DEV" DOUBLE , 
		  "MAX_DEV" DOUBLE )   
		 IN "MDSHORT" ; 

-- DDL Statements for primary key on Table "PERF    "."PERFORMANCE"

ALTER TABLE "PERF    "."PERFORMANCE" 
	ADD PRIMARY KEY
		("TRACE_SET_ID",
		 "TRACE_LABEL");



------------------------------------------------
-- DDL Statements for table "PERF    "."BLOCKS"
------------------------------------------------
 
 CREATE TABLE "PERF    "."BLOCKS"  (
		  "BLOCK_ID" VARCHAR(16) NOT NULL , 
		  "PX" INTEGER NOT NULL , 
		  "PY" INTEGER NOT NULL , 
		  "PZ" INTEGER NOT NULL , 
		  "NUMPSETS" INTEGER NOT NULL )   
		 IN "MDSHORT" ; 

-- DDL Statements for primary key on Table "PERF    "."BLOCKS"

ALTER TABLE "PERF    "."BLOCKS" 
	ADD PRIMARY KEY
		("BLOCK_ID");









COMMIT WORK;

CONNECT RESET;

TERMINATE;
