-- This CLP file was created using DB2LOOK Version 8.2
-- Timestamp: Thu May 18 03:20:29 EDT 2006
-- Database Name: MDSETUP        
-- Database Manager Version: DB2/6000 Version 8.2.4        
-- Database Codepage: 819
-- Database Collating Sequence is: UNIQUE


CONNECT TO MDSETUP;



------------------------------------------------
-- DDL Statements for table "RGERMAIN"."TRACE_GROUP"
------------------------------------------------
 
 CREATE TABLE "RGERMAIN"."TRACE_GROUP"  (
		  "GROUP_ID" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY (  
		    START WITH +1  
		    INCREMENT BY +1  
		    MINVALUE +1  
		    MAXVALUE +2147483647  
		    NO CYCLE  
		    CACHE 20  
		    NO ORDER ) , 
		  "CREATOR" VARCHAR(30) NOT NULL , 
		  "CREATED" TIMESTAMP NOT NULL , 
		  "DESC" VARCHAR(1024) )   
		 IN "USERSPACE1" ; 

-- DDL Statements for primary key on Table "RGERMAIN"."TRACE_GROUP"

ALTER TABLE "RGERMAIN"."TRACE_GROUP" 
	ADD PRIMARY KEY
		("GROUP_ID");



------------------------------------------------
-- DDL Statements for table "RGERMAIN"."TRACE_SET"
------------------------------------------------
 
 CREATE TABLE "RGERMAIN"."TRACE_SET"  (
		  "TRACE_SET_ID" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY (  
		    START WITH +1  
		    INCREMENT BY +1  
		    MINVALUE +1  
		    MAXVALUE +2147483647  
		    NO CYCLE  
		    CACHE 20  
		    NO ORDER ) , 
		  "GROUP_ID" INTEGER NOT NULL , 
		  "NODE_COUNT" INTEGER NOT NULL , 
		  "BIN_FILE" VARCHAR(128) NOT NULL )   
		 IN "USERSPACE1" ; 

-- DDL Statements for primary key on Table "RGERMAIN"."TRACE_SET"

ALTER TABLE "RGERMAIN"."TRACE_SET" 
	ADD PRIMARY KEY
		("TRACE_SET_ID");



------------------------------------------------
-- DDL Statements for table "RGERMAIN"."TRACE_ID"
------------------------------------------------
 
 CREATE TABLE "RGERMAIN"."TRACE_ID"  (
		  "TRACE_SET_ID" INTEGER NOT NULL , 
		  "TRACE_ID" INTEGER NOT NULL , 
		  "NODE_ID" INTEGER NOT NULL , 
		  "TRACE_TYPE" INTEGER NOT NULL , 
		  "TRACE_LABEL" VARCHAR(48) NOT NULL , 
		  "TRACE_DESC" VARCHAR(256) NOT NULL )   
		 IN "USERSPACE1" ; 

-- DDL Statements for primary key on Table "RGERMAIN"."TRACE_ID"

ALTER TABLE "RGERMAIN"."TRACE_ID" 
	ADD PRIMARY KEY
		("TRACE_SET_ID",
		 "TRACE_ID",
		 "NODE_ID");



------------------------------------------------
-- DDL Statements for table "RGERMAIN"."JOB"
------------------------------------------------
 
 CREATE TABLE "RGERMAIN"."JOB"  (
		  "JOBID" INTEGER NOT NULL , 
		  "JOBNAME" CHAR(48) NOT NULL , 
		  "USERNAME" CHAR(32) NOT NULL , 
		  "BLOCKID" CHAR(16) , 
		  "EXECUTABLE" VARCHAR(256) NOT NULL )   
		 IN "USERSPACE1" ; 

-- DDL Statements for primary key on Table "RGERMAIN"."JOB"

ALTER TABLE "RGERMAIN"."JOB" 
	ADD PRIMARY KEY
		("JOBID",
		 "JOBNAME");



------------------------------------------------
-- DDL Statements for table "RGERMAIN"."JOBHISTORY"
------------------------------------------------
 
 CREATE TABLE "RGERMAIN"."JOBHISTORY"  (
		  "JOBID" INTEGER NOT NULL , 
		  "JOBNAME" CHAR(48) NOT NULL , 
		  "CHANGED" TIMESTAMP NOT NULL , 
		  "STATUS" CHAR(1) NOT NULL )   
		 IN "USERSPACE1" ; 

-- DDL Statements for primary key on Table "RGERMAIN"."JOBHISTORY"

ALTER TABLE "RGERMAIN"."JOBHISTORY" 
	ADD PRIMARY KEY
		("JOBID",
		 "JOBNAME",
		 "CHANGED");



------------------------------------------------
-- DDL Statements for table "RGERMAIN"."TOYDATA"
------------------------------------------------
 
 CREATE TABLE "RGERMAIN"."TOYDATA"  (
		  "JOBID" INTEGER NOT NULL , 
		  "MODE" CHAR(6) NOT NULL , 
		  "TOTAL_NODES" INTEGER NOT NULL , 
		  "MEM_PER_NODE" INTEGER NOT NULL , 
		  "READ_NODES" INTEGER NOT NULL , 
		  "READS_PER_NODE" INTEGER NOT NULL , 
		  "THR_PER_READ_NODE" INTEGER NOT NULL , 
		  "TIME" DOUBLE NOT NULL , 
		  "RATE" DOUBLE NOT NULL )   
		 IN "USERSPACE1" ; 

-- DDL Statements for primary key on Table "RGERMAIN"."TOYDATA"

ALTER TABLE "RGERMAIN"."TOYDATA" 
	ADD PRIMARY KEY
		("JOBID",
		 "MODE",
		 "MEM_PER_NODE",
		 "READ_NODES",
		 "THR_PER_READ_NODE");



------------------------------------------------
-- DDL Statements for table "RGERMAIN"."TOYBATCH"
------------------------------------------------
 
 CREATE TABLE "RGERMAIN"."TOYBATCH"  (
		  "BATCHID" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY (  
		    START WITH +1  
		    INCREMENT BY +1  
		    MINVALUE +1  
		    MAXVALUE +2147483647  
		    NO CYCLE  
		    CACHE 20  
		    NO ORDER ) , 
		  "PATH" VARCHAR(128) , 
		  "DESC" VARCHAR(128) )   
		 IN "USERSPACE1" ; 

-- DDL Statements for primary key on Table "RGERMAIN"."TOYBATCH"

ALTER TABLE "RGERMAIN"."TOYBATCH" 
	ADD PRIMARY KEY
		("BATCHID");



------------------------------------------------
-- DDL Statements for table "RGERMAIN"."TOYJOB"
------------------------------------------------
 
 CREATE TABLE "RGERMAIN"."TOYJOB"  (
		  "JOBID" INTEGER NOT NULL , 
		  "BATCHID" INTEGER NOT NULL , 
		  "PX" INTEGER NOT NULL , 
		  "PY" INTEGER NOT NULL , 
		  "PZ" INTEGER NOT NULL )   
		 IN "USERSPACE1" ; 

-- DDL Statements for primary key on Table "RGERMAIN"."TOYJOB"

ALTER TABLE "RGERMAIN"."TOYJOB" 
	ADD PRIMARY KEY
		("BATCHID",
		 "JOBID");


-- DDL Statements for unique constraints on Table "RGERMAIN"."TOYJOB"

ALTER TABLE "RGERMAIN"."TOYJOB" 
	ADD CONSTRAINT "TOYJOB_UNQ_001" UNIQUE
		("JOBID");






----------------------------

-- DDL Statements for Views

----------------------------
SET CURRENT SCHEMA = "RGERMAIN";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","RGERMAIN";
create view proc_mesh (trace_set_id, p_x, p_y, p_z) as with px (trace_set_id,
px) as (select trace_set_id, substr(value, 1, 4) from perf.trace_set_data
where name='p_x'), py (trace_set_id, py) as (select trace_set_id, substr(value,
1, 4) from perf.trace_set_data where name='p_y'), pz (trace_set_id, pz)
as (select trace_set_id, substr(value, 1, 4) from perf.trace_set_data where
name='p_z') select px.trace_set_id, px.px, py.py, pz.pz from px,py,pz where
px.trace_set_id=py.trace_set_id and px.trace_set_id=pz.trace_set_id;



-- DDL Statements for foreign keys on Table "RGERMAIN"."TRACE_SET"

ALTER TABLE "RGERMAIN"."TRACE_SET" 
	ADD CONSTRAINT "SQL040419222236561" FOREIGN KEY
		("GROUP_ID")
	REFERENCES "RGERMAIN"."TRACE_GROUP"
		("GROUP_ID")
	ON DELETE CASCADE
	ON UPDATE NO ACTION
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for foreign keys on Table "RGERMAIN"."TRACE_ID"

ALTER TABLE "RGERMAIN"."TRACE_ID" 
	ADD CONSTRAINT "SQL040419222237011" FOREIGN KEY
		("TRACE_SET_ID")
	REFERENCES "RGERMAIN"."TRACE_SET"
		("TRACE_SET_ID")
	ON DELETE CASCADE
	ON UPDATE NO ACTION
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for foreign keys on Table "RGERMAIN"."JOBHISTORY"

ALTER TABLE "RGERMAIN"."JOBHISTORY" 
	ADD CONSTRAINT "SQL050618211416950" FOREIGN KEY
		("JOBID",
		 "JOBNAME")
	REFERENCES "RGERMAIN"."JOB"
		("JOBID",
		 "JOBNAME")
	ON DELETE CASCADE
	ON UPDATE NO ACTION
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for foreign keys on Table "RGERMAIN"."TOYDATA"

ALTER TABLE "RGERMAIN"."TOYDATA" 
	ADD CONSTRAINT "TOYDATA_FKC_001" FOREIGN KEY
		("JOBID")
	REFERENCES "RGERMAIN"."TOYJOB"
		("JOBID")
	ON DELETE CASCADE
	ON UPDATE NO ACTION
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for foreign keys on Table "RGERMAIN"."TOYJOB"

ALTER TABLE "RGERMAIN"."TOYJOB" 
	ADD CONSTRAINT "SQL060406120934101" FOREIGN KEY
		("BATCHID")
	REFERENCES "RGERMAIN"."TOYBATCH"
		("BATCHID")
	ON DELETE CASCADE
	ON UPDATE NO ACTION
	ENFORCED
	ENABLE QUERY OPTIMIZATION;


COMMIT WORK;

CONNECT RESET;

TERMINATE;
