# Source reship list
VPATH = ..
ILIST = \
  flataschar.hpp \
  makefile.aix \
  new.hpp \
  Makefile.ode
flataschar.hpp_IDIR = $(BG_SRC)/bgfe/pk/util_cpp/include/
makefile.aix_IDIR = $(BG_SRC)/bgfe/pk/util_cpp/include/
new.hpp_IDIR = $(BG_SRC)/bgfe/pk/util_cpp/include/
Makefile.ode_IDIR = $(BG_SRC)/bgfe/pk/util_cpp/include/source_ship/
.include <$(RULES_MK)>
