# Source reship list
VPATH = ..
ILIST = \
  platform.cpp \
  sqrt_wrap.cpp \
  Makefile.ode
platform.cpp_IDIR = $(BG_SRC)/bgfe/pk/platform/src/
sqrt_wrap.cpp_IDIR = $(BG_SRC)/bgfe/pk/platform/src/
Makefile.ode_IDIR = $(BG_SRC)/bgfe/pk/platform/src/source_ship/
.include <$(RULES_MK)>
