PROGRAMS = \
	testMRG32k3aEngine${PROG_SUFF} \
	testNormalDeviate${PROG_SUFF} \

testMRG32k3aEngine${PROG_SUFF}_OFILES = \
	testMRG32k3aEngine${OBJ_SUFF} \

testNormalDeviate${PROG_SUFF}_OFILES = \
	testNormalDeviate${OBJ_SUFF} \

OBJECTS = \
	testMRG32k3aEngine${OBJ_SUFF} \
	testNormalDeviate${OBJ_SUFF} \

LIBS = $(LIB_PREF)MRG32k3aEngine$(LIB_SUFF)

EXPLIBS = $(LIBRARIES)
EXPLIBDIR = /usr/lib/

ILIST = \
	testMRG32k3aEngine${PROG_SUFF} \
	testNormalDeviate${PROG_SUFF} \

CFLAGS += -D NO_PK_PLATFORM

IDIR = $(BG_BIN)/utils/

.if defined(RESHIP_SOURCE)
ILIST += Makefile.ode
Makefile.ode_IDIR = $(BG_SRC)/./BlueMatter/random/src/
INSTALL_STANDARD_SUBDIRS = $(SUBDIRS) $(STANDARD_SUBDIRS) source_ship
.endif # RESHIP_SOURCE
.include <$(RULES_MK)>
