EXPINC_SUBDIRS = \
  include \

OBJECTS_SUBDIRS = \
  src \

SUBDIRS = \
  $(EXPINC_SUBDIRS) \
  $(OBJECTS_SUBDIRS) \


.if defined(RESHIP_SOURCE)
ILIST += Makefile.ode
Makefile.ode_IDIR = $(BG_SRC)/./pktools/traceutils/
INSTALL_STANDARD_SUBDIRS = $(SUBDIRS) $(STANDARD_SUBDIRS) source_ship
.endif # RESHIP_SOURCE
.include <$(RULES_MK)>
