EXPINC_SUBDIRS = \
 include \

#.if !empty(CONTEXT:Mrios_aix*) || !empty(CONTEXT:Mrios64_aix*) || defined(TRY_LINUX_BUILD_ANYWAY)

OBJECTS_SUBDIRS = rdg \
	analysis \
	tools \
	src \
	
#.endif

SUBDIRS = $(EXPINC_SUBDIRS) \
	  $(OBJECTS_SUBDIRS) \


.include <$(RULES_MK)>
