from __future__ import print_function
# routine to drive an analysis routine through RunResults.txt
# this version works on the combined set of runs generated by MultiRun
# Runs within a MultRun are grouped into RunSets for which only one parameter
# is varied, e.g. timestep size
#
# Arguments: (1) directory containing run data
#            (2) analysis object that implements runSet(rVector), finalize(),
#                and setColumnDict(columnDict) methods

from runresults import *
import os
import warnings

def multianalyze(analysis):

    # use RunResults object to contain data from RunResults.txt file
    # RunResults object is essentially a dictionary of sequences indexed
    # by the the RunSetID. Each element of the sequence is a RunSet object.
    runResults = RunResults('../RunResults.txt')
    
    # now we can spool through each entry in this new dictionary to analyze
    # each RunSet
    for elt in runResults.keys():
        print("run set =", elt)
        analysis.runSet(runResults[elt])
    analysis.finalize()
