#!/bin/ksh
../../build

#  -D PKFXLOG_ALL -D PKDEBUG_PATH \
#mpCC_r -g -D MPI -D PKFXLOG -D PKFXLOG_GLOBJECT \
mpCC_r -g -D MPI -D PKFXLOG  -D PKFXLOG_ALL \
-I $HOME/GFEBUILDROOT/include $1.cpp  \
../../pkmain/src/main.cpp \
../../util_comm/src/mpi.cpp \
../../globject/src/globject.cpp \
../../pthread/src/pthread.cpp \
../../fxlogger/src/fxlogger.cpp \
../../exception/src/exception.cpp \
../../reactor/src/reactor.cpp \
-o $1_mpi.exe
