#
#
CMSCMPDIRVALUE=foxfm/pk/

include $(BASE)/makedef.aix

all: hdrs

# These header files are to shipped as part of the Framework product

CMSPUBLINCS=\
	$(CMSPRDBLDINCDIR)/pk/pktrace_aix_ras.hpp \
	$(CMSPRDBLDINCDIR)/pk/pktrace_pk.hpp \
	$(CMSPRDBLDINCDIR)/pk/pktrace.hpp \
	$(CMSPRDBLDINCDIR)/pk/trace_control.hpp

CMSPRIVINCS=

hdrs: $(CMSPUBLINCS) $(CMSPRIVINCS)

libs:

bins:

clean:
	rm -f $(CMSPUBLINCS) $(CMSPRIVINCS)

$(CMSPUBLINCS) $(CMSPRIVINCS): $$(@F)
	rm -f $@
	$(INSTALL_HDR) $? $@
