# Source reship list
VPATH = ..
ILIST = \
  makefile.aix \
  Makefile.ode
makefile.aix_IDIR = $(BG_SRC)/bgfe/pk/util_aix/
Makefile.ode_IDIR = $(BG_SRC)/bgfe/pk/util_aix/source_ship/
.include <$(RULES_MK)>
