# Source reship list
VPATH = ..
ILIST = \
  makefile.aix \
  pthread.cpp \
  pthread_aix4.cpp \
  Makefile.ode
makefile.aix_IDIR = $(BG_SRC)/bgfe/pk/pthread/src/
pthread.cpp_IDIR = $(BG_SRC)/bgfe/pk/pthread/src/
pthread_aix4.cpp_IDIR = $(BG_SRC)/bgfe/pk/pthread/src/
Makefile.ode_IDIR = $(BG_SRC)/bgfe/pk/pthread/src/source_ship/
.include <$(RULES_MK)>
