SUBDIRS = \
 include \

EXPINC_SUBDIRS = $(SUBDIRS)

.if defined(RESHIP_SOURCE)
ILIST += Makefile.ode
Makefile.ode_IDIR = $(BG_SRC)/./BlueMatter/plimpton/
.endif # RESHIP_SOURCE
.include <$(RULES_MK)>
