# Source reship list
VPATH = ..
ILIST = \
  build \
  build_mpi \
  queueMPI.cpp \
  queue_latency00.cpp \
  queue_set_latency00.cpp \
  Makefile.ode
build_IDIR = $(BG_SRC)/bgfe/pk/queues/test/
build_mpi_IDIR = $(BG_SRC)/bgfe/pk/queues/test/
queueMPI.cpp_IDIR = $(BG_SRC)/bgfe/pk/queues/test/
queue_latency00.cpp_IDIR = $(BG_SRC)/bgfe/pk/queues/test/
queue_set_latency00.cpp_IDIR = $(BG_SRC)/bgfe/pk/queues/test/
Makefile.ode_IDIR = $(BG_SRC)/bgfe/pk/queues/test/source_ship/
.include <$(RULES_MK)>
