# Source reship list
VPATH = ..
ILIST = \
#  makefile.aix \
#  pktrace.cpp \
  pktrace_pk.cpp \
#  resize_pk.cpp \
  Makefile.ode
#makefile.aix_IDIR = $(BG_SRC)/bgfe/pk/trace/src/
#pktrace.cpp_IDIR = $(BG_SRC)/bgfe/pk/trace/src/
pktrace_pk.cpp_IDIR = $(BG_SRC)/bgfe/pk/trace/src/
#resize_pk.cpp_IDIR = $(BG_SRC)/bgfe/pk/trace/src/
Makefile.ode_IDIR = $(BG_SRC)/bgfe/pk/trace/src/source_ship/
.include <$(RULES_MK)>
