BG_AUXILIARY = 1
INCLUDES = \
  db2_relay.hpp \
  db2_relay_defines.hpp

EXPINCDIR = /usr/include/inmemdb/

ILIST =       $(INCLUDES)

IDIR    = $(BG_INCLUDE)/inmemdb/


.if defined(RESHIP_SOURCE)
ILIST += Makefile.ode
Makefile.ode_IDIR = $(BG_SRC)/./inmemdb/db2_relay/include/
.endif # RESHIP_SOURCE
.include <$(RULES_MK)>
