# Source reship list
VPATH = ..
ILIST = \
  random.hpp \
  Makefile.ode
random.hpp_IDIR = $(BG_SRC)/BlueMatter/random/include/
Makefile.ode_IDIR = $(BG_SRC)/BlueMatter/random/include/source_ship/
.include <$(RULES_MK)>
