# Source reship list
VPATH = ..
ILIST = \
  makefile.aix \
  reactor.hpp \
  Makefile.ode
makefile.aix_IDIR = $(BG_SRC)/bgfe/pk/reactor/include/
reactor.hpp_IDIR = $(BG_SRC)/bgfe/pk/reactor/include/
Makefile.ode_IDIR = $(BG_SRC)/bgfe/pk/reactor/include/source_ship/
.include <$(RULES_MK)>
