INCLUDES = \
  PPL_ProtocolDriver.hpp \
  PPL_SystemIF.hpp \
  PPL_UserIF.hpp \

EXPINCDIR = /usr/include/PhasedPipeline/

IDIR = $(BG_INCLUDE)/PhasedPipeline/
ILIST = $(INCLUDES)

.if defined(RESHIP_SOURCE)
ILIST += Makefile.ode
Makefile.ode_IDIR = $(BG_SRC)/./bgfe/PhasedPipeline/include/
INSTALL_STANDARD_SUBDIRS = $(SUBDIRS) $(STANDARD_SUBDIRS) source_ship
.endif # RESHIP_SOURCE
.include <$(RULES_MK)>
