OFILES  = \
	random$(OBJ_SUFF) \

OBJECTS = $(OFILES)

LIBRARIES = $(LIB_PREF)pkrandom$(LIB_SUFF)

EXPLIBS = $(LIBRARIES)
EXPLIBDIR = /usr/lib/

ILIST = $(LIBRARIES) \
	random.cpp \

IDIR = $(BG_LIB)/
random.cpp_IDIR = $(BG_SRC)/pk/

.if defined(RESHIP_SOURCE)
ILIST += Makefile.ode
Makefile.ode_IDIR = $(BG_SRC)/./bgfe/pk/random/src/
INSTALL_STANDARD_SUBDIRS = $(SUBDIRS) $(STANDARD_SUBDIRS) source_ship
.endif # RESHIP_SOURCE
.include <$(RULES_MK)>
