# Source reship list
VPATH = ..
ILIST = \
  LowerTriangleIndex.hpp \
  probspecgen.hpp \
  Makefile.ode
LowerTriangleIndex.hpp_IDIR = $(BG_SRC)/BlueMatter/probspecgen/include/
probspecgen.hpp_IDIR = $(BG_SRC)/BlueMatter/probspecgen/include/
Makefile.ode_IDIR = $(BG_SRC)/BlueMatter/probspecgen/include/source_ship/
.include <$(RULES_MK)>
