# Source reship list
VPATH = ..
ILIST = \
  Broadcast.hpp \
  Reduce.hpp \
  Makefile.ode
Broadcast.hpp_IDIR = $(BG_SRC)/bgfe/pk/collective/include/
Reduce.hpp_IDIR = $(BG_SRC)/bgfe/pk/collective/include/
Makefile.ode_IDIR = $(BG_SRC)/bgfe/pk/collective/include/source_ship/
.include <$(RULES_MK)>
