INCLUDES = \
        pktrace.hpp \
        pktrace_aix_ras.hpp \
        pktrace_pk.hpp \
        pktrace_perfctr.hpp \
        trace_control.hpp \


EXPINCDIR = /usr/include/pk/

IDIR = $(BG_INCLUDE)/pk/
ILIST = $(INCLUDES)

.if defined(RESHIP_SOURCE)
ILIST += Makefile.ode
Makefile.ode_IDIR = $(BG_SRC)/./bgfe/pk/trace/include/
INSTALL_STANDARD_SUBDIRS = $(SUBDIRS) $(STANDARD_SUBDIRS) source_ship
.endif # RESHIP_SOURCE
.include <$(RULES_MK)>
