BG_AUXILIARY = 1
INCLUDES = \
  SortGen.hpp \
  IndySort.hpp \

EXPINCDIR = /usr/include/inmemdb/

ILIST =       $(INCLUDES)
IDIR    = $(BG_INCLUDE)/inmemdb/


.if defined(RESHIP_SOURCE)
ILIST += Makefile.ode
Makefile.ode_IDIR = $(BG_SRC)/./inmemdb/sort/include/
.endif # RESHIP_SOURCE
.include <$(RULES_MK)>
