INCLUDES = \
	treebroadcast.h    \
	treebroadcast.hpp  \
	treereduce.h       \
	treereduce.hpp     \

EXPINCDIR = /usr/include/pk/


IDIR = $(BG_INCLUDE)/pk/
ILIST = $(INCLUDES)

.include <$(RULES_MK)>
