# Source reship list
VPATH = ..
ILIST = \
  UDFRegistryDB2Setup.java \
  UDF_Category.del \
  UDF_Record.del \
  UDF_Variable.del \
  load_udf_del_script \
  Makefile.ode
UDFRegistryDB2Setup.java_IDIR = $(BG_SRC)/BlueMatter/probspecdb2/com/ibm/bluematter/udf_registry/
UDF_Category.del_IDIR = $(BG_SRC)/BlueMatter/probspecdb2/com/ibm/bluematter/udf_registry/
UDF_Record.del_IDIR = $(BG_SRC)/BlueMatter/probspecdb2/com/ibm/bluematter/udf_registry/
UDF_Variable.del_IDIR = $(BG_SRC)/BlueMatter/probspecdb2/com/ibm/bluematter/udf_registry/
load_udf_del_script_IDIR = $(BG_SRC)/BlueMatter/probspecdb2/com/ibm/bluematter/udf_registry/
Makefile.ode_IDIR = $(BG_SRC)/BlueMatter/probspecdb2/com/ibm/bluematter/udf_registry/source_ship/
.include <$(RULES_MK)>
