# Source reship list
VPATH = ..
ILIST = \
  DynamicVariableManager.hpp \
  Makefile.ode
DynamicVariableManager.hpp_IDIR = $(BG_SRC)/BlueMatter/dynvarmgr/include/
Makefile.ode_IDIR = $(BG_SRC)/BlueMatter/dynvarmgr/include/source_ship/
.include <$(RULES_MK)>
