# Source reship list
VPATH = ..
ILIST = \
  build_mpi \
  iv00.cpp \
  Makefile.ode
build_mpi_IDIR = $(BG_SRC)/bgfe/pk/rpc/test/
iv00.cpp_IDIR = $(BG_SRC)/bgfe/pk/rpc/test/
Makefile.ode_IDIR = $(BG_SRC)/bgfe/pk/rpc/test/source_ship/
.include <$(RULES_MK)>
