# Source reship list
VPATH = ..
ILIST = \
  BondListAsGraph.java \
  ConnectedSubgraphs.java \
  GraphSeparation.java \
  IntegerPairRep.java \
  Pair.java \
  ProbspecGenerator.java \
  ProbspecgenDB2.java \
  SiteTypeRep.java \
  UDF_RegistryIF.java \
  Makefile.ode
BondListAsGraph.java_IDIR = $(BG_SRC)/BlueMatter/probspecdb2/com/ibm/bluematter/db2probspec/
ConnectedSubgraphs.java_IDIR = $(BG_SRC)/BlueMatter/probspecdb2/com/ibm/bluematter/db2probspec/
GraphSeparation.java_IDIR = $(BG_SRC)/BlueMatter/probspecdb2/com/ibm/bluematter/db2probspec/
IntegerPairRep.java_IDIR = $(BG_SRC)/BlueMatter/probspecdb2/com/ibm/bluematter/db2probspec/
Pair.java_IDIR = $(BG_SRC)/BlueMatter/probspecdb2/com/ibm/bluematter/db2probspec/
ProbspecGenerator.java_IDIR = $(BG_SRC)/BlueMatter/probspecdb2/com/ibm/bluematter/db2probspec/
ProbspecgenDB2.java_IDIR = $(BG_SRC)/BlueMatter/probspecdb2/com/ibm/bluematter/db2probspec/
SiteTypeRep.java_IDIR = $(BG_SRC)/BlueMatter/probspecdb2/com/ibm/bluematter/db2probspec/
UDF_RegistryIF.java_IDIR = $(BG_SRC)/BlueMatter/probspecdb2/com/ibm/bluematter/db2probspec/
Makefile.ode_IDIR = $(BG_SRC)/BlueMatter/probspecdb2/com/ibm/bluematter/db2probspec/source_ship/
.include <$(RULES_MK)>
