# Source reship list
VPATH = ..
ILIST = \
  README \
  psf2xml.pl \
  Makefile.ode
README_IDIR = $(BG_SRC)/BlueMatter/xmlgen/charmm22/
psf2xml.pl_IDIR = $(BG_SRC)/BlueMatter/xmlgen/charmm22/
Makefile.ode_IDIR = $(BG_SRC)/BlueMatter/xmlgen/charmm22/source_ship/
.include <$(RULES_MK)>
