BG_AUXILIARY = DB2 

INCLUDES += \
  to_be_generated.hpp \
  Table.hpp \
  RecordBufferManager.hpp \
  RandomNodeList.hpp \
  QueryResult.hpp \
  QueryProcessor.hpp \

EXPINCDIR = /usr/include/inmemdb/

ILIST  =  $(INCLUDES)
IDIR   =  $(BG_INCLUDE)/inmemdb/


.if defined(RESHIP_SOURCE)
ILIST += Makefile.ode
Makefile.ode_IDIR = $(BG_SRC)/./inmemdb/containers/include/
.endif # RESHIP_SOURCE
.include <$(RULES_MK)>
