BG_AUXILIARY = DB2

OBJECTS += \
  test_container_iterators${OBJ_SUFF} \

OFILES += \
  test_container_iterators${OBJ_SUFF} \

LIBRARIES = $(LIB_PREF)inmemdb$(LIB_SUFF)

LIBS += \
  $(LIB_PREF)db2cli$(LIB_SUFF) \
  $(LIB_PREF)inmemdb$(LIB_SUFF)
  
PROGRAMS = \
  test_container_iterators$(PROG_SUFF) \

test_container_iterators$(PROG_SUFF)_OFILES = \
  test_container_iterators${OBJ_SUFF} \

#IDIR = $(BG_BIN)/inmemdb/
#ILIST = $(PROGRAMS)

.if defined(RESHIP_SOURCE)
ILIST += Makefile.ode
Makefile.ode_IDIR = $(BG_SRC)/./inmemdb/containers/test/
.endif # RESHIP_SOURCE
.include <$(RULES_MK)>
