# Source reship list
VPATH = ..
ILIST = \
  makefile.aix \
  mpi.cpp \
  Makefile.ode
makefile.aix_IDIR = $(BG_SRC)/bgfe/pk/util_comm/src/
mpi.cpp_IDIR = $(BG_SRC)/bgfe/pk/util_comm/src/
Makefile.ode_IDIR = $(BG_SRC)/bgfe/pk/util_comm/src/source_ship/
.include <$(RULES_MK)>
