# Source reship list
VPATH = ..
ILIST = \
  P3MElib.hpp \
  Makefile.ode
P3MElib.hpp_IDIR = $(BG_SRC)/BlueMatter/p3me/include/
Makefile.ode_IDIR = $(BG_SRC)/BlueMatter/p3me/include/source_ship/
.include <$(RULES_MK)>
