# Source reship list
VPATH = ..
ILIST = \
  DropSchema.java \
  DropSystem.java \
  DumpSysId.java \
  Makefile.ode
DropSchema.java_IDIR = $(BG_SRC)/BlueMatter/probspecdb2/com/ibm/bluematter/utils/
DropSystem.java_IDIR = $(BG_SRC)/BlueMatter/probspecdb2/com/ibm/bluematter/utils/
DumpSysId.java_IDIR = $(BG_SRC)/BlueMatter/probspecdb2/com/ibm/bluematter/utils/
Makefile.ode_IDIR = $(BG_SRC)/BlueMatter/probspecdb2/com/ibm/bluematter/utils/source_ship/
.include <$(RULES_MK)>
