# Source reship list
VPATH = ..
ILIST = \
  fxlogger.hpp \
  makefile.aix \
  Makefile.ode
fxlogger.hpp_IDIR = $(BG_SRC)/bgfe/pk/fxlogger/include/
makefile.aix_IDIR = $(BG_SRC)/bgfe/pk/fxlogger/include/
Makefile.ode_IDIR = $(BG_SRC)/bgfe/pk/fxlogger/include/source_ship/
.include <$(RULES_MK)>
