# Source reship list
VPATH = ..
ILIST = \
  enkp.charmm.xml \
  enkp.psf \
  par_all22_prot.inp \
  top_all22_prot.inp \
  Makefile.ode
enkp.charmm.xml_IDIR = $(BG_SRC)/BlueMatter/xmlgen/charmm22/example/
enkp.psf_IDIR = $(BG_SRC)/BlueMatter/xmlgen/charmm22/example/
par_all22_prot.inp_IDIR = $(BG_SRC)/BlueMatter/xmlgen/charmm22/example/
top_all22_prot.inp_IDIR = $(BG_SRC)/BlueMatter/xmlgen/charmm22/example/
Makefile.ode_IDIR = $(BG_SRC)/BlueMatter/xmlgen/charmm22/example/source_ship/
.include <$(RULES_MK)>
