OBJECTS         = \
	timelim$(OBJ_SUFF)

PROGRAMS        = \
	timelim$(PROG_SUFF)

IDIR                = $(BG_BIN)/utils/

ILIST   =       $(PROGRAMS)

.if defined(RESHIP_SOURCE)
ILIST += Makefile.ode
Makefile.ode_IDIR = $(BG_SRC)/./bgfe/pk/util_test/src/
INSTALL_STANDARD_SUBDIRS = $(SUBDIRS) $(STANDARD_SUBDIRS) source_ship
.endif # RESHIP_SOURCE
.include <$(RULES_MK)>
