# Source reship list
VPATH = ..
ILIST = \
  CreateDB2Tables.java \
  ProbspecDB2Setup.java \
  splitoutput.pl \
  xml2db2.pl \
  xml2del.pl \
  xml2sdel.xsl \
  Makefile.ode
CreateDB2Tables.java_IDIR = $(BG_SRC)/BlueMatter/probspecdb2/com/ibm/bluematter/xml2db2/
ProbspecDB2Setup.java_IDIR = $(BG_SRC)/BlueMatter/probspecdb2/com/ibm/bluematter/xml2db2/
splitoutput.pl_IDIR = $(BG_SRC)/BlueMatter/probspecdb2/com/ibm/bluematter/xml2db2/
xml2db2.pl_IDIR = $(BG_SRC)/BlueMatter/probspecdb2/com/ibm/bluematter/xml2db2/
xml2del.pl_IDIR = $(BG_SRC)/BlueMatter/probspecdb2/com/ibm/bluematter/xml2db2/
xml2sdel.xsl_IDIR = $(BG_SRC)/BlueMatter/probspecdb2/com/ibm/bluematter/xml2db2/
Makefile.ode_IDIR = $(BG_SRC)/BlueMatter/probspecdb2/com/ibm/bluematter/xml2db2/source_ship/
.include <$(RULES_MK)>
