# Source reship list
VPATH = ..
ILIST = \
  Buildconf \
  Buildconf.exp \
  Makeconf \
  sb.conf \
  Makefile.ode
Buildconf_IDIR = $(BG_SRC)/BlueMatter/tgtbuild/
Buildconf.exp_IDIR = $(BG_SRC)/BlueMatter/tgtbuild/
Makeconf_IDIR = $(BG_SRC)/BlueMatter/tgtbuild/
sb.conf_IDIR = $(BG_SRC)/BlueMatter/tgtbuild/
Makefile.ode_IDIR = $(BG_SRC)/BlueMatter/tgtbuild/source_ship/
.include <$(RULES_MK)>
