# Source reship list
VPATH = ..
ILIST = \
  ThreadCreate.hpp \
  makefile.aix \
  pthread.hpp \
  pthread_aix4.hpp \
  Makefile.ode
ThreadCreate.hpp_IDIR = $(BG_SRC)/bgfe/pk/pthread/include/
makefile.aix_IDIR = $(BG_SRC)/bgfe/pk/pthread/include/
pthread.hpp_IDIR = $(BG_SRC)/bgfe/pk/pthread/include/
pthread_aix4.hpp_IDIR = $(BG_SRC)/bgfe/pk/pthread/include/
Makefile.ode_IDIR = $(BG_SRC)/bgfe/pk/pthread/include/source_ship/
.include <$(RULES_MK)>
