
IDIR            = $(BG_BIN)/utils/

ILIST           = \
  rmsde_vs_ts.pl  \
  stripEnergy.pl  \
  find_nb_tune.awk \
  enkp_respa.ksh

.if defined(RESHIP_SOURCE)
ILIST += Makefile.ode
Makefile.ode_IDIR = $(BG_SRC)/./BlueMatter/util/analysis/
INSTALL_STANDARD_SUBDIRS = $(SUBDIRS) $(STANDARD_SUBDIRS) source_ship
.endif # RESHIP_SOURCE
.include <$(RULES_MK)>
