LIBS    =       $(PKSPILIBS)

CFLAGS += $(SPICFLAGS) $(SMPCFLAGS)

OFILES         = \
	topology$(OBJ_SUFF)

PROGRAMS        = \
	topology$(PROG_SUFF)

IDIR                = $(BG_BIN)/kernels/spi/tree/

ILIST   =       $(PROGRAMS)


.if defined(RESHIP_SOURCE)
ILIST += Makefile.ode
makefile.ode_IDIR = $(BG_SRC)/./BlueMatter/ivt/tree/topology/
.endif # RESHIP_SOURCE
.include <$(RULES_MK)>
