# Source reship list
VPATH = ..
ILIST = \
  makefile.aix \
  rpc.hpp \
  Makefile.ode
makefile.aix_IDIR = $(BG_SRC)/bgfe/pk/rpc/include/
rpc.hpp_IDIR = $(BG_SRC)/bgfe/pk/rpc/include/
Makefile.ode_IDIR = $(BG_SRC)/bgfe/pk/rpc/include/source_ship/
.include <$(RULES_MK)>
