# Source reship list
VPATH = ..
ILIST = \
  BoundingBox.hpp \
  PeriodicImage.hpp \
  XYZ.hpp \
  Makefile.ode
BoundingBox.hpp_IDIR = $(BG_SRC)/BlueMatter/geometry/include/
PeriodicImage.hpp_IDIR = $(BG_SRC)/BlueMatter/geometry/include/
XYZ.hpp_IDIR = $(BG_SRC)/BlueMatter/geometry/include/
Makefile.ode_IDIR = $(BG_SRC)/BlueMatter/geometry/include/source_ship/
.include <$(RULES_MK)>
