OFILES  = \
  exception$(OBJ_SUFF) \

OBJECTS = $(OFILES)

LIBRARIES = $(LIB_PREF)pkexception$(LIB_SUFF)

EXPLIBS = $(LIBRARIES)
EXPLIBDIR = /usr/lib/

ILIST = $(LIBRARIES) \
  exception.cpp \

IDIR = $(BG_LIB)/

exception.cpp_IDIR = $(BG_SRC)/pk/

.if defined(RESHIP_SOURCE)
ILIST += Makefile.ode
Makefile.ode_IDIR = $(BG_SRC)/./bgfe/pk/exception/src/
INSTALL_STANDARD_SUBDIRS = $(SUBDIRS) $(STANDARD_SUBDIRS) source_ship
.endif # RESHIP_SOURCE
.include <$(RULES_MK)>
