# Source reship list
VPATH = ..
ILIST = \
  Grid2D.hpp \
  Makefile.ode
Grid2D.hpp_IDIR = $(BG_SRC)/bgfe/pk/ltopology/include/
Makefile.ode_IDIR = $(BG_SRC)/bgfe/pk/ltopology/include/source_ship/
.include <$(RULES_MK)>
