BG_AUXILIARY = 1
EXPINC_SUBDIRS = \
 include \

EXPLIB_SUBDIRS = \
 src \

OBJECTS_SUBDIRS = \
 src \

SUBDIRS = \
     $(EXPINC_SUBDIRS) \
     $(OBJECTS_SUBDIRS) \


.if defined(RESHIP_SOURCE)
ILIST += Makefile.ode
Makefile.ode_IDIR = $(BG_SRC)/./BlueMatter/probspecgen/
.endif # RESHIP_SOURCE
.include <$(RULES_MK)>
