# Source reship list
VPATH = ..
ILIST = \
  random.cpp \
  Makefile.ode
random.cpp_IDIR = $(BG_SRC)/BlueMatter/random/src/
Makefile.ode_IDIR = $(BG_SRC)/BlueMatter/random/src/source_ship/
.include <$(RULES_MK)>
