# Makefile for GFE base directory
#

CMSCMPDIRVALUE=foxfm/pk/

include $(BASE)/makedef.aix

all: hdrs libs bins objs

hdrs:
	+cd include; $(MAKE) $(MAKEFLAGS) -f $(MAKEF) $@

libs bins:
	+cd src; $(MAKE) $(MAKEFLAGS) -f $(MAKEF) $@
