INCLUDES = \
	UDF_RegistryIF.hpp \
	UDF_Binding.hpp \
	UDF_HelperWater.hpp \
	UDF_HelperGroup.hpp \
	UDF_State.hpp \
	UDF_HelperLekner.hpp \

EXPINCDIR = /usr/include/BlueMatter/

IDIR = $(BG_INCLUDE)/BlueMatter/
ILIST = $(INCLUDES)

.if defined(RESHIP_SOURCE)
ILIST += Makefile.ode
Makefile.ode_IDIR = $(BG_SRC)/./BlueMatter/udf/include/
INSTALL_STANDARD_SUBDIRS = $(SUBDIRS) $(STANDARD_SUBDIRS) source_ship
.endif # RESHIP_SOURCE
.include <$(RULES_MK)>
