# Source reship list
VPATH = ..
ILIST = \
  timelim.cpp \
  Makefile.ode
timelim.cpp_IDIR = $(BG_SRC)/bgfe/pk/util_test/src/
Makefile.ode_IDIR = $(BG_SRC)/bgfe/pk/util_test/src/source_ship/
.include <$(RULES_MK)>
