# Source reship list
VPATH = ..
ILIST = \
  makefile.aix \
  z.PPL_ProtocolDriver.hpp \
  z.PPL_SystemIF.hpp \
  z.PPL_UserIF.hpp \
  Makefile.ode
makefile.aix_IDIR = $(BG_SRC)/bgfe/PhasedPipeline/
z.PPL_ProtocolDriver.hpp_IDIR = $(BG_SRC)/bgfe/PhasedPipeline/
z.PPL_SystemIF.hpp_IDIR = $(BG_SRC)/bgfe/PhasedPipeline/
z.PPL_UserIF.hpp_IDIR = $(BG_SRC)/bgfe/PhasedPipeline/
Makefile.ode_IDIR = $(BG_SRC)/bgfe/PhasedPipeline/source_ship/
.include <$(RULES_MK)>
