# Source reship list
VPATH = ..
ILIST = \
  exception.hpp \
  execption.hpp \
  makefile.aix \
  Makefile.ode
exception.hpp_IDIR = $(BG_SRC)/bgfe/pk/exception/include/
execption.hpp_IDIR = $(BG_SRC)/bgfe/pk/exception/include/
makefile.aix_IDIR = $(BG_SRC)/bgfe/pk/exception/include/
Makefile.ode_IDIR = $(BG_SRC)/bgfe/pk/exception/include/source_ship/
.include <$(RULES_MK)>
