INCLUDES = \
  mt19937.hpp \
  RandomNumberGeneratorIf.hpp \
  RngMrg32k3a.hpp \
#	testrandomwrapper.hpp \
#	gsl_random_wrapper.hpp \

EXPINCDIR = /usr/include/BlueMatter/

IDIR = $(BG_INCLUDE)/BlueMatter/
ILIST = $(INCLUDES)

.if defined(RESHIP_SOURCE)
ILIST += Makefile.ode
Makefile.ode_IDIR = $(BG_SRC)/./BlueMatter/random/include/
INSTALL_STANDARD_SUBDIRS = $(SUBDIRS) $(STANDARD_SUBDIRS) source_ship
.endif # RESHIP_SOURCE
.include <$(RULES_MK)>
