INCLUDES = \
  datagram_queue.hpp \
  queue_set.hpp \
  shmem_queue.hpp \

EXPINCDIR = /usr/include/pk/

IDIR = $(BG_INCLUDE)/pk/
ILIST = $(INCLUDES)

.if defined(RESHIP_SOURCE)
ILIST += Makefile.ode
Makefile.ode_IDIR = $(BG_SRC)/./bgfe/pk/queues/include/
INSTALL_STANDARD_SUBDIRS = $(SUBDIRS) $(STANDARD_SUBDIRS) source_ship
.endif # RESHIP_SOURCE
.include <$(RULES_MK)>
