# Source reship list
VPATH = ..
ILIST = \
  makefile.aix \
  pkrnew.cpp \
  Makefile.ode
makefile.aix_IDIR = $(BG_SRC)/bgfe/pk/rnew/src/
pkrnew.cpp_IDIR = $(BG_SRC)/bgfe/pk/rnew/src/
Makefile.ode_IDIR = $(BG_SRC)/bgfe/pk/rnew/src/source_ship/
.include <$(RULES_MK)>
