OFILES  = \
	globject$(OBJ_SUFF) \

OBJECTS = $(OFILES)

LIBRARIES = $(LIB_PREF)pkglobject$(LIB_SUFF)

EXPLIBS = $(LIBRARIES)
EXPLIBDIR = /usr/lib/

ILIST = $(LIBRARIES) \
	globject.cpp \

CFLAGS += $(SMPCFLAGS)

IDIR = $(BG_LIB)/
globject.cpp_IDIR = $(BG_SRC)/pk/

.if defined(RESHIP_SOURCE)
ILIST += Makefile.ode
Makefile.ode_IDIR = $(BG_SRC)/./bgfe/pk/globject/src/
INSTALL_STANDARD_SUBDIRS = $(SUBDIRS) $(STANDARD_SUBDIRS) source_ship
.endif # RESHIP_SOURCE
.include <$(RULES_MK)>
