# Source reship list
VPATH = ..
ILIST = \
  PhysicalTopology.hpp \
  Makefile.ode
PhysicalTopology.hpp_IDIR = $(BG_SRC)/bgfe/pk/ptopology/include/
Makefile.ode_IDIR = $(BG_SRC)/bgfe/pk/ptopology/include/source_ship/
.include <$(RULES_MK)>
