EXPINC_SUBDIRS = \
 include \

OBJECTS_SUBDIRS = \
	src \
	unit_test \

EXPLIB_SUBDIRS = $(OBJECTS_SUBDIRS)
STANDARD_SUBDIRS = $(EXPINC_SUBDIRS) $(OBJECTS_SUBDIRS)

.if defined(RESHIP_SOURCE)
ILIST += Makefile.ode
Makefile.ode_IDIR = $(BG_SRC)/./BlueMatter/random/
.endif # RESHIP_SOURCE
.include <$(RULES_MK)>
