# Source reship list
VPATH = ..
ILIST = \
  makefile.aix \
  Makefile.ode
makefile.aix_IDIR = $(BG_SRC)/bgfe/pk/reactor/
Makefile.ode_IDIR = $(BG_SRC)/bgfe/pk/reactor/source_ship/
.include <$(RULES_MK)>
