# Source reship list
VPATH = ..
ILIST = \
  probspecgen.cpp \
  Makefile.ode
probspecgen.cpp_IDIR = $(BG_SRC)/BlueMatter/probspecgen/src/
Makefile.ode_IDIR = $(BG_SRC)/BlueMatter/probspecgen/src/source_ship/
.include <$(RULES_MK)>
