# Source reship list
VPATH = ..
ILIST = \
  README \
  README.OPLS \
  README.xmlprobspec \
  build \
  Makefile.ode
README_IDIR = $(BG_SRC)/BlueMatter/probspec/
README.OPLS_IDIR = $(BG_SRC)/BlueMatter/probspec/
README.xmlprobspec_IDIR = $(BG_SRC)/BlueMatter/probspec/
build_IDIR = $(BG_SRC)/BlueMatter/probspec/
Makefile.ode_IDIR = $(BG_SRC)/BlueMatter/probspec/source_ship/
.include <$(RULES_MK)>
