-- This CLP file was created using DB2LOOK Version 7.2
-- Timestamp: Sun Jul 21 21:48:30 EDT 2002
-- Database Name: MDSETUP        
-- Database Manager Version: DB2/6000 Version 7.2.3        
-- Database Codepage: 819


CONNECT TO MDSETUP;



------------------------------------------------
-- DDL Statements for table "MDSYSTEM"."SYSTEM"
------------------------------------------------
 
 CREATE TABLE "MDSYSTEM"."SYSTEM"  (
		  "SYS_ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH +0 , INCREMENT BY +1 , CACHE 20 ) , 
		  "SYS_DESC" VARCHAR(30) NOT NULL , 
		  "CREATOR" VARCHAR(40) NOT NULL , 
		  "CREATED" TIMESTAMP NOT NULL , 
		  "SYS_CLASS" VARCHAR(60) NOT NULL )   
		 IN "MDSHORT" ; 

-- DDL Statements for primary key on Table "MDSYSTEM"."SYSTEM"

ALTER TABLE "MDSYSTEM"."SYSTEM" 
	ADD PRIMARY KEY
		("SYS_ID");



------------------------------------------------
-- DDL Statements for table "MDSYSTEM"."CHAIN"
------------------------------------------------
 
 CREATE TABLE "MDSYSTEM"."CHAIN"  (
		  "SYS_ID" INTEGER NOT NULL , 
		  "CHAIN_ID" INTEGER NOT NULL , 
		  "CHAIN_DESC" VARCHAR(100) )   
		 IN "MDSHORT" ; 

-- DDL Statements for primary key on Table "MDSYSTEM"."CHAIN"

ALTER TABLE "MDSYSTEM"."CHAIN" 
	ADD PRIMARY KEY
		("SYS_ID",
		 "CHAIN_ID");



------------------------------------------------
-- DDL Statements for table "MDSYSTEM"."CHEM_COMP_INSTANCE"
------------------------------------------------
 
 CREATE TABLE "MDSYSTEM"."CHEM_COMP_INSTANCE"  (
		  "SYS_ID" INTEGER NOT NULL , 
		  "CC_INSTANCE_ID" INTEGER NOT NULL , 
		  "COMPONENT_NAME" VARCHAR(100) NOT NULL )   
		 IN "MDSHORT" ; 

-- DDL Statements for primary key on Table "MDSYSTEM"."CHEM_COMP_INSTANCE"

ALTER TABLE "MDSYSTEM"."CHEM_COMP_INSTANCE" 
	ADD PRIMARY KEY
		("SYS_ID",
		 "CC_INSTANCE_ID");



------------------------------------------------
-- DDL Statements for table "MDSYSTEM"."SPECIFIC_MOLECULE"
------------------------------------------------
 
 CREATE TABLE "MDSYSTEM"."SPECIFIC_MOLECULE"  (
		  "SYS_ID" INTEGER NOT NULL , 
		  "MOL_ID" INTEGER NOT NULL , 
		  "MOLECULE_NAME" VARCHAR(60) NOT NULL , 
		  "CLASS" VARCHAR(60) NOT NULL , 
		  "GENERIC_NAME" VARCHAR(60) , 
		  "PDB_ID" VARCHAR(60) )   
		 IN "MDSHORT" ; 

-- DDL Statements for primary key on Table "MDSYSTEM"."SPECIFIC_MOLECULE"

ALTER TABLE "MDSYSTEM"."SPECIFIC_MOLECULE" 
	ADD PRIMARY KEY
		("SYS_ID",
		 "MOL_ID");



------------------------------------------------
-- DDL Statements for table "MDSYSTEM"."MOLECULE_INSTANCE"
------------------------------------------------
 
 CREATE TABLE "MDSYSTEM"."MOLECULE_INSTANCE"  (
		  "SYS_ID" INTEGER NOT NULL , 
		  "MOL_INSTANCE_ID" INTEGER NOT NULL , 
		  "MOL_ID" INTEGER NOT NULL )   
		 IN "MDSHORT" ; 

-- DDL Statements for primary key on Table "MDSYSTEM"."MOLECULE_INSTANCE"

ALTER TABLE "MDSYSTEM"."MOLECULE_INSTANCE" 
	ADD PRIMARY KEY
		("SYS_ID",
		 "MOL_INSTANCE_ID");



------------------------------------------------
-- DDL Statements for table "MDSYSTEM"."MONOMER_INSTANCE"
------------------------------------------------
 
 CREATE TABLE "MDSYSTEM"."MONOMER_INSTANCE"  (
		  "SYS_ID" INTEGER NOT NULL , 
		  "CHAIN_ID" INTEGER NOT NULL , 
		  "MONOMER_ORDINAL" INTEGER NOT NULL , 
		  "CC_INSTANCE_ID" INTEGER NOT NULL )   
		 IN "MDSHORT" ; 

-- DDL Statements for primary key on Table "MDSYSTEM"."MONOMER_INSTANCE"

ALTER TABLE "MDSYSTEM"."MONOMER_INSTANCE" 
	ADD PRIMARY KEY
		("SYS_ID",
		 "CHAIN_ID",
		 "MONOMER_ORDINAL");



------------------------------------------------
-- DDL Statements for table "MDSYSTEM"."PARAMTUPLELIST"
------------------------------------------------
 
 CREATE TABLE "MDSYSTEM"."PARAMTUPLELIST"  (
		  "SYS_ID" INTEGER NOT NULL , 
		  "PARAM_TUPLE_LIST_ID" INTEGER NOT NULL , 
		  "PARAM_TUPLE_DESC" VARCHAR(40) )   
		 IN "MDSHORT" ; 

-- DDL Statements for primary key on Table "MDSYSTEM"."PARAMTUPLELIST"

ALTER TABLE "MDSYSTEM"."PARAMTUPLELIST" 
	ADD PRIMARY KEY
		("SYS_ID",
		 "PARAM_TUPLE_LIST_ID");



------------------------------------------------
-- DDL Statements for table "MDSYSTEM"."PARAMTUPLESPEC"
------------------------------------------------
 
 CREATE TABLE "MDSYSTEM"."PARAMTUPLESPEC"  (
		  "SYS_ID" INTEGER NOT NULL , 
		  "PARAM_TUPLE_LIST_ID" INTEGER NOT NULL , 
		  "PARAM_ID" INTEGER NOT NULL , 
		  "PARAM_TYPE" INTEGER , 
		  "PARAM_NAME" VARCHAR(40) )   
		 IN "MDSHORT" ; 

-- DDL Statements for primary key on Table "MDSYSTEM"."PARAMTUPLESPEC"

ALTER TABLE "MDSYSTEM"."PARAMTUPLESPEC" 
	ADD PRIMARY KEY
		("SYS_ID",
		 "PARAM_TUPLE_LIST_ID",
		 "PARAM_ID");



------------------------------------------------
-- DDL Statements for table "MDSYSTEM"."PARAMTUPLE"
------------------------------------------------
 
 CREATE TABLE "MDSYSTEM"."PARAMTUPLE"  (
		  "SYS_ID" INTEGER NOT NULL , 
		  "PARAM_TUPLE_LIST_ID" INTEGER NOT NULL , 
		  "PARAM_TUPLE_ID" INTEGER NOT NULL )   
		 IN "MDSHORT" ; 

-- DDL Statements for primary key on Table "MDSYSTEM"."PARAMTUPLE"

ALTER TABLE "MDSYSTEM"."PARAMTUPLE" 
	ADD PRIMARY KEY
		("SYS_ID",
		 "PARAM_TUPLE_LIST_ID",
		 "PARAM_TUPLE_ID");



------------------------------------------------
-- DDL Statements for table "MDSYSTEM"."PARAMTUPLEDATA"
------------------------------------------------
 
 CREATE TABLE "MDSYSTEM"."PARAMTUPLEDATA"  (
		  "SYS_ID" INTEGER NOT NULL , 
		  "PARAM_TUPLE_LIST_ID" INTEGER NOT NULL , 
		  "PARAM_TUPLE_ID" INTEGER NOT NULL , 
		  "PARAM_ID" INTEGER NOT NULL , 
		  "PARAM_VALUE" VARCHAR(40) )   
		 IN "MDSHORT" ; 

-- DDL Statements for primary key on Table "MDSYSTEM"."PARAMTUPLEDATA"

ALTER TABLE "MDSYSTEM"."PARAMTUPLEDATA" 
	ADD PRIMARY KEY
		("SYS_ID",
		 "PARAM_TUPLE_LIST_ID",
		 "PARAM_TUPLE_ID",
		 "PARAM_ID");



------------------------------------------------
-- DDL Statements for table "MDSYSTEM"."SITETUPLELIST"
------------------------------------------------
 
 CREATE TABLE "MDSYSTEM"."SITETUPLELIST"  (
		  "SYS_ID" INTEGER NOT NULL , 
		  "SITE_TUPLE_LIST_ID" INTEGER NOT NULL , 
		  "SITE_TUPLE_DESC" VARCHAR(40) )   
		 IN "MDSHORT" ; 

-- DDL Statements for primary key on Table "MDSYSTEM"."SITETUPLELIST"

ALTER TABLE "MDSYSTEM"."SITETUPLELIST" 
	ADD PRIMARY KEY
		("SYS_ID",
		 "SITE_TUPLE_LIST_ID");



------------------------------------------------
-- DDL Statements for table "MDSYSTEM"."UDF_INVOCATION_TABLE"
------------------------------------------------
 
 CREATE TABLE "MDSYSTEM"."UDF_INVOCATION_TABLE"  (
		  "SYS_ID" INTEGER NOT NULL , 
		  "UDF_ID" VARCHAR(60) NOT NULL , 
		  "SITE_TUPLE_LIST_ID" INTEGER NOT NULL , 
		  "PARAM_TUPLE_LIST_ID" INTEGER )   
		 IN "MDSHORT" ; 

-- DDL Statements for primary key on Table "MDSYSTEM"."UDF_INVOCATION_TABLE"

ALTER TABLE "MDSYSTEM"."UDF_INVOCATION_TABLE" 
	ADD PRIMARY KEY
		("SYS_ID",
		 "UDF_ID",
		 "SITE_TUPLE_LIST_ID");



------------------------------------------------
-- DDL Statements for table "MDSYSTEM"."SITETUPLE"
------------------------------------------------
 
 CREATE TABLE "MDSYSTEM"."SITETUPLE"  (
		  "SYS_ID" INTEGER NOT NULL , 
		  "SITE_TUPLE_LIST_ID" INTEGER NOT NULL , 
		  "SITE_TUPLE_ID" INTEGER NOT NULL )   
		 IN "MDSHORT" ; 

-- DDL Statements for primary key on Table "MDSYSTEM"."SITETUPLE"

ALTER TABLE "MDSYSTEM"."SITETUPLE" 
	ADD PRIMARY KEY
		("SYS_ID",
		 "SITE_TUPLE_LIST_ID",
		 "SITE_TUPLE_ID");



------------------------------------------------
-- DDL Statements for table "MDSYSTEM"."SITE"
------------------------------------------------
 
 CREATE TABLE "MDSYSTEM"."SITE"  (
		  "SYS_ID" INTEGER NOT NULL , 
		  "SITE_ID" INTEGER NOT NULL , 
		  "CC_INSTANCE_ID" INTEGER , 
		  "MOL_INSTANCE_ID" INTEGER , 
		  "EPSILON" VARCHAR(50) , 
		  "RMIN" VARCHAR(50) , 
		  "EPSILON14" VARCHAR(50) , 
		  "RMIN14" VARCHAR(50) , 
		  "ATOMIC_MASS" VARCHAR(50) , 
		  "CHARGE" VARCHAR(60) , 
		  "ATOM_TAG" VARCHAR(60) , 
		  "COMPONENT_NAME" VARCHAR(60) , 
		  "ELEMENT_SYMBOL" VARCHAR(10) )   
		 IN "MDSHORT" ; 

-- DDL Statements for primary key on Table "MDSYSTEM"."SITE"

ALTER TABLE "MDSYSTEM"."SITE" 
	ADD PRIMARY KEY
		("SYS_ID",
		 "SITE_ID");



------------------------------------------------
-- DDL Statements for table "MDSYSTEM"."SITETUPLEDATA"
------------------------------------------------
 
 CREATE TABLE "MDSYSTEM"."SITETUPLEDATA"  (
		  "SYS_ID" INTEGER NOT NULL , 
		  "SITE_TUPLE_LIST_ID" INTEGER NOT NULL , 
		  "SITE_TUPLE_ID" INTEGER NOT NULL , 
		  "SITE_ORDINAL" INTEGER NOT NULL , 
		  "SITE_ID" INTEGER NOT NULL )   
		 IN "MDSHORT" ; 

-- DDL Statements for primary key on Table "MDSYSTEM"."SITETUPLEDATA"

ALTER TABLE "MDSYSTEM"."SITETUPLEDATA" 
	ADD PRIMARY KEY
		("SYS_ID",
		 "SITE_TUPLE_LIST_ID",
		 "SITE_TUPLE_ID",
		 "SITE_ORDINAL");



------------------------------------------------
-- DDL Statements for table "MDSYSTEM"."GROUP"
------------------------------------------------
 
 CREATE TABLE "MDSYSTEM"."GROUP"  (
		  "SYS_ID" INTEGER NOT NULL , 
		  "GROUP_ID" INTEGER NOT NULL , 
		  "GROUP_TYPE" VARCHAR(60) NOT NULL )   
		 IN "MDSHORT" ; 

-- DDL Statements for primary key on Table "MDSYSTEM"."GROUP"

ALTER TABLE "MDSYSTEM"."GROUP" 
	ADD PRIMARY KEY
		("SYS_ID",
		 "GROUP_ID");



------------------------------------------------
-- DDL Statements for table "MDSYSTEM"."GROUP_SITE"
------------------------------------------------
 
 CREATE TABLE "MDSYSTEM"."GROUP_SITE"  (
		  "SYS_ID" INTEGER NOT NULL , 
		  "GROUP_ID" INTEGER NOT NULL , 
		  "SITE_ID" INTEGER NOT NULL )   
		 IN "MDSHORT" ; 

-- DDL Statements for primary key on Table "MDSYSTEM"."GROUP_SITE"

ALTER TABLE "MDSYSTEM"."GROUP_SITE" 
	ADD PRIMARY KEY
		("SYS_ID",
		 "GROUP_ID",
		 "SITE_ID");



------------------------------------------------
-- DDL Statements for table "MDSYSTEM"."SITE_PARAM_SPEC"
------------------------------------------------
 
 CREATE TABLE "MDSYSTEM"."SITE_PARAM_SPEC"  (
		  "SYS_ID" INTEGER NOT NULL , 
		  "PARAM_ID" INTEGER NOT NULL , 
		  "TYPE_ID" INTEGER NOT NULL , 
		  "NAME" VARCHAR(60) NOT NULL )   
		 IN "MDSHORT" ; 

-- DDL Statements for primary key on Table "MDSYSTEM"."SITE_PARAM_SPEC"

ALTER TABLE "MDSYSTEM"."SITE_PARAM_SPEC" 
	ADD PRIMARY KEY
		("SYS_ID",
		 "PARAM_ID");



------------------------------------------------
-- DDL Statements for table "MDSYSTEM"."SITE_PARAM"
------------------------------------------------
 
 CREATE TABLE "MDSYSTEM"."SITE_PARAM"  (
		  "SYS_ID" INTEGER NOT NULL , 
		  "SITE_ID" INTEGER NOT NULL , 
		  "PARAM_ID" INTEGER NOT NULL , 
		  "VALUE" VARCHAR(60) NOT NULL )   
		 IN "MDSHORT" ; 

-- DDL Statements for primary key on Table "MDSYSTEM"."SITE_PARAM"

ALTER TABLE "MDSYSTEM"."SITE_PARAM" 
	ADD PRIMARY KEY
		("SYS_ID",
		 "SITE_ID",
		 "PARAM_ID");



------------------------------------------------
-- DDL Statements for table "MDSYSTEM"."BOND"
------------------------------------------------
 
 CREATE TABLE "MDSYSTEM"."BOND"  (
		  "SYS_ID" INTEGER NOT NULL , 
		  "BOND_ID" INTEGER NOT NULL , 
		  "SITE_ID1" INTEGER NOT NULL , 
		  "SITE_ID2" INTEGER NOT NULL , 
		  "BOND_TYPE" INTEGER )   
		 IN "MDSHORT" ; 

-- DDL Statements for primary key on Table "MDSYSTEM"."BOND"

ALTER TABLE "MDSYSTEM"."BOND" 
	ADD PRIMARY KEY
		("SYS_ID",
		 "BOND_ID");



------------------------------------------------
-- DDL Statements for table "MDSYSTEM"."GLOBAL_PARAMETER_TYPE"
------------------------------------------------
 
 CREATE TABLE "MDSYSTEM"."GLOBAL_PARAMETER_TYPE"  (
		  "SYS_ID" INTEGER NOT NULL , 
		  "PARAM_TYPE" INTEGER NOT NULL , 
		  "PARAM_DESC" VARCHAR(60) )   
		 IN "MDSHORT" ; 

-- DDL Statements for primary key on Table "MDSYSTEM"."GLOBAL_PARAMETER_TYPE"

ALTER TABLE "MDSYSTEM"."GLOBAL_PARAMETER_TYPE" 
	ADD PRIMARY KEY
		("SYS_ID",
		 "PARAM_TYPE");



------------------------------------------------
-- DDL Statements for table "MDSYSTEM"."GLOBAL_PARAMETER"
------------------------------------------------
 
 CREATE TABLE "MDSYSTEM"."GLOBAL_PARAMETER"  (
		  "SYS_ID" INTEGER NOT NULL , 
		  "PARAM_ID" VARCHAR(20) NOT NULL , 
		  "PARAM_TYPE" INTEGER NOT NULL , 
		  "SYMBOLIC_CONSTANT" INTEGER , 
		  "PARAM_VALUE" VARCHAR(60) )   
		 IN "MDSHORT" ; 

-- DDL Statements for primary key on Table "MDSYSTEM"."GLOBAL_PARAMETER"

ALTER TABLE "MDSYSTEM"."GLOBAL_PARAMETER" 
	ADD PRIMARY KEY
		("SYS_ID",
		 "PARAM_ID");




-- DDL Statements for foreign keys on Table "MDSYSTEM"."SYSTEM"

ALTER TABLE "MDSYSTEM"."SYSTEM" 
	ADD CONSTRAINT "SQL020508213230300" FOREIGN KEY
		("SYS_CLASS")
	REFERENCES "EXPERIMENT"."SYSTEM_CLASS"
		("SYS_CLASS")
	ON DELETE NO ACTION
	ON UPDATE NO ACTION;


-- DDL Statements for foreign keys on Table "MDSYSTEM"."CHAIN"

ALTER TABLE "MDSYSTEM"."CHAIN" 
	ADD CONSTRAINT "SQL020508213230610" FOREIGN KEY
		("SYS_ID")
	REFERENCES "MDSYSTEM"."SYSTEM"
		("SYS_ID")
	ON DELETE CASCADE
	ON UPDATE NO ACTION;


-- DDL Statements for foreign keys on Table "MDSYSTEM"."CHEM_COMP_INSTANCE"

ALTER TABLE "MDSYSTEM"."CHEM_COMP_INSTANCE" 
	ADD CONSTRAINT "SQL020508213230950" FOREIGN KEY
		("SYS_ID")
	REFERENCES "MDSYSTEM"."SYSTEM"
		("SYS_ID")
	ON DELETE CASCADE
	ON UPDATE NO ACTION;

ALTER TABLE "MDSYSTEM"."CHEM_COMP_INSTANCE" 
	ADD CONSTRAINT "SQL020508213230980" FOREIGN KEY
		("COMPONENT_NAME")
	REFERENCES "CHEM    "."CHEMICAL_COMPONENT"
		("COMPONENT_NAME")
	ON DELETE CASCADE
	ON UPDATE NO ACTION;


-- DDL Statements for foreign keys on Table "MDSYSTEM"."SPECIFIC_MOLECULE"

ALTER TABLE "MDSYSTEM"."SPECIFIC_MOLECULE" 
	ADD CONSTRAINT "SQL020508213231310" FOREIGN KEY
		("SYS_ID")
	REFERENCES "MDSYSTEM"."SYSTEM"
		("SYS_ID")
	ON DELETE CASCADE
	ON UPDATE NO ACTION;

ALTER TABLE "MDSYSTEM"."SPECIFIC_MOLECULE" 
	ADD CONSTRAINT "SQL020508213231340" FOREIGN KEY
		("CLASS")
	REFERENCES "CHEM    "."MOLECULE_TYPE"
		("CLASS")
	ON DELETE CASCADE
	ON UPDATE NO ACTION;


-- DDL Statements for foreign keys on Table "MDSYSTEM"."MOLECULE_INSTANCE"

ALTER TABLE "MDSYSTEM"."MOLECULE_INSTANCE" 
	ADD CONSTRAINT "SQL020508213231640" FOREIGN KEY
		("SYS_ID")
	REFERENCES "MDSYSTEM"."SYSTEM"
		("SYS_ID")
	ON DELETE CASCADE
	ON UPDATE NO ACTION;

ALTER TABLE "MDSYSTEM"."MOLECULE_INSTANCE" 
	ADD CONSTRAINT "SQL020508213231670" FOREIGN KEY
		("SYS_ID",
		 "MOL_ID")
	REFERENCES "MDSYSTEM"."SPECIFIC_MOLECULE"
		("SYS_ID",
		 "MOL_ID")
	ON DELETE CASCADE
	ON UPDATE NO ACTION;


-- DDL Statements for foreign keys on Table "MDSYSTEM"."MONOMER_INSTANCE"

ALTER TABLE "MDSYSTEM"."MONOMER_INSTANCE" 
	ADD CONSTRAINT "SQL020508213232000" FOREIGN KEY
		("SYS_ID")
	REFERENCES "MDSYSTEM"."SYSTEM"
		("SYS_ID")
	ON DELETE CASCADE
	ON UPDATE NO ACTION;

ALTER TABLE "MDSYSTEM"."MONOMER_INSTANCE" 
	ADD CONSTRAINT "SQL020508213232030" FOREIGN KEY
		("SYS_ID",
		 "CHAIN_ID")
	REFERENCES "MDSYSTEM"."CHAIN"
		("SYS_ID",
		 "CHAIN_ID")
	ON DELETE CASCADE
	ON UPDATE NO ACTION;

ALTER TABLE "MDSYSTEM"."MONOMER_INSTANCE" 
	ADD CONSTRAINT "SQL020508213232050" FOREIGN KEY
		("SYS_ID",
		 "CC_INSTANCE_ID")
	REFERENCES "MDSYSTEM"."CHEM_COMP_INSTANCE"
		("SYS_ID",
		 "CC_INSTANCE_ID")
	ON DELETE CASCADE
	ON UPDATE NO ACTION;


-- DDL Statements for foreign keys on Table "MDSYSTEM"."PARAMTUPLELIST"

ALTER TABLE "MDSYSTEM"."PARAMTUPLELIST" 
	ADD CONSTRAINT "SQL020508213232400" FOREIGN KEY
		("SYS_ID")
	REFERENCES "MDSYSTEM"."SYSTEM"
		("SYS_ID")
	ON DELETE CASCADE
	ON UPDATE NO ACTION;


-- DDL Statements for foreign keys on Table "MDSYSTEM"."PARAMTUPLESPEC"

ALTER TABLE "MDSYSTEM"."PARAMTUPLESPEC" 
	ADD CONSTRAINT "SQL020508213232750" FOREIGN KEY
		("SYS_ID",
		 "PARAM_TUPLE_LIST_ID")
	REFERENCES "MDSYSTEM"."PARAMTUPLELIST"
		("SYS_ID",
		 "PARAM_TUPLE_LIST_ID")
	ON DELETE CASCADE
	ON UPDATE NO ACTION;


-- DDL Statements for foreign keys on Table "MDSYSTEM"."PARAMTUPLE"

ALTER TABLE "MDSYSTEM"."PARAMTUPLE" 
	ADD CONSTRAINT "SQL020508213233120" FOREIGN KEY
		("SYS_ID",
		 "PARAM_TUPLE_LIST_ID")
	REFERENCES "MDSYSTEM"."PARAMTUPLELIST"
		("SYS_ID",
		 "PARAM_TUPLE_LIST_ID")
	ON DELETE CASCADE
	ON UPDATE NO ACTION;


-- DDL Statements for foreign keys on Table "MDSYSTEM"."PARAMTUPLEDATA"

ALTER TABLE "MDSYSTEM"."PARAMTUPLEDATA" 
	ADD CONSTRAINT "SQL020508213233440" FOREIGN KEY
		("SYS_ID",
		 "PARAM_TUPLE_LIST_ID")
	REFERENCES "MDSYSTEM"."PARAMTUPLELIST"
		("SYS_ID",
		 "PARAM_TUPLE_LIST_ID")
	ON DELETE CASCADE
	ON UPDATE NO ACTION;


-- DDL Statements for foreign keys on Table "MDSYSTEM"."SITETUPLELIST"

ALTER TABLE "MDSYSTEM"."SITETUPLELIST" 
	ADD CONSTRAINT "SQL020508213233750" FOREIGN KEY
		("SYS_ID")
	REFERENCES "MDSYSTEM"."SYSTEM"
		("SYS_ID")
	ON DELETE CASCADE
	ON UPDATE NO ACTION;


-- DDL Statements for foreign keys on Table "MDSYSTEM"."UDF_INVOCATION_TABLE"

ALTER TABLE "MDSYSTEM"."UDF_INVOCATION_TABLE" 
	ADD CONSTRAINT "SQL020508213234080" FOREIGN KEY
		("SYS_ID",
		 "SITE_TUPLE_LIST_ID")
	REFERENCES "MDSYSTEM"."SITETUPLELIST"
		("SYS_ID",
		 "SITE_TUPLE_LIST_ID")
	ON DELETE CASCADE
	ON UPDATE NO ACTION;

ALTER TABLE "MDSYSTEM"."UDF_INVOCATION_TABLE" 
	ADD CONSTRAINT "SQL020508213234110" FOREIGN KEY
		("SYS_ID",
		 "PARAM_TUPLE_LIST_ID")
	REFERENCES "MDSYSTEM"."PARAMTUPLELIST"
		("SYS_ID",
		 "PARAM_TUPLE_LIST_ID")
	ON DELETE CASCADE
	ON UPDATE NO ACTION;


-- DDL Statements for foreign keys on Table "MDSYSTEM"."SITETUPLE"

ALTER TABLE "MDSYSTEM"."SITETUPLE" 
	ADD CONSTRAINT "SQL020508213234480" FOREIGN KEY
		("SYS_ID",
		 "SITE_TUPLE_LIST_ID")
	REFERENCES "MDSYSTEM"."SITETUPLELIST"
		("SYS_ID",
		 "SITE_TUPLE_LIST_ID")
	ON DELETE CASCADE
	ON UPDATE NO ACTION;


-- DDL Statements for foreign keys on Table "MDSYSTEM"."SITE"

ALTER TABLE "MDSYSTEM"."SITE" 
	ADD CONSTRAINT "SQL020508213234850" FOREIGN KEY
		("SYS_ID")
	REFERENCES "MDSYSTEM"."SYSTEM"
		("SYS_ID")
	ON DELETE CASCADE
	ON UPDATE NO ACTION;

ALTER TABLE "MDSYSTEM"."SITE" 
	ADD CONSTRAINT "SQL020508213234870" FOREIGN KEY
		("SYS_ID",
		 "MOL_INSTANCE_ID")
	REFERENCES "MDSYSTEM"."MOLECULE_INSTANCE"
		("SYS_ID",
		 "MOL_INSTANCE_ID")
	ON DELETE CASCADE
	ON UPDATE NO ACTION;

ALTER TABLE "MDSYSTEM"."SITE" 
	ADD CONSTRAINT "SQL020508213234890" FOREIGN KEY
		("SYS_ID",
		 "CC_INSTANCE_ID")
	REFERENCES "MDSYSTEM"."CHEM_COMP_INSTANCE"
		("SYS_ID",
		 "CC_INSTANCE_ID")
	ON DELETE CASCADE
	ON UPDATE NO ACTION;

ALTER TABLE "MDSYSTEM"."SITE" 
	ADD CONSTRAINT "SQL020508213234910" FOREIGN KEY
		("ELEMENT_SYMBOL")
	REFERENCES "CHEM    "."ELEMENTS"
		("ELEMENT_SYMBOL")
	ON DELETE CASCADE
	ON UPDATE NO ACTION;

ALTER TABLE "MDSYSTEM"."SITE" 
	ADD CONSTRAINT "SQL020508213234930" FOREIGN KEY
		("COMPONENT_NAME",
		 "ATOM_TAG")
	REFERENCES "CHEM    "."ATOM_TAG_TABLE"
		("COMPONENT_NAME",
		 "ATOM_TAG")
	ON DELETE CASCADE
	ON UPDATE NO ACTION;


-- DDL Statements for foreign keys on Table "MDSYSTEM"."SITETUPLEDATA"

ALTER TABLE "MDSYSTEM"."SITETUPLEDATA" 
	ADD CONSTRAINT "SQL020508213235280" FOREIGN KEY
		("SYS_ID",
		 "SITE_TUPLE_LIST_ID")
	REFERENCES "MDSYSTEM"."SITETUPLELIST"
		("SYS_ID",
		 "SITE_TUPLE_LIST_ID")
	ON DELETE CASCADE
	ON UPDATE NO ACTION;

ALTER TABLE "MDSYSTEM"."SITETUPLEDATA" 
	ADD CONSTRAINT "SQL020508213235300" FOREIGN KEY
		("SYS_ID",
		 "SITE_ID")
	REFERENCES "MDSYSTEM"."SITE"
		("SYS_ID",
		 "SITE_ID")
	ON DELETE CASCADE
	ON UPDATE NO ACTION;



-- DDL Statements for foreign keys on Table "MDSYSTEM"."GROUP_SITE"

ALTER TABLE "MDSYSTEM"."GROUP_SITE" 
	ADD CONSTRAINT "SQL020508213235930" FOREIGN KEY
		("SYS_ID",
		 "SITE_ID")
	REFERENCES "MDSYSTEM"."SITE"
		("SYS_ID",
		 "SITE_ID")
	ON DELETE CASCADE
	ON UPDATE NO ACTION;

ALTER TABLE "MDSYSTEM"."GROUP_SITE" 
	ADD CONSTRAINT "SQL020508213235960" FOREIGN KEY
		("SYS_ID",
		 "GROUP_ID")
	REFERENCES "MDSYSTEM"."GROUP"
		("SYS_ID",
		 "GROUP_ID")
	ON DELETE CASCADE
	ON UPDATE NO ACTION;


-- DDL Statements for foreign keys on Table "MDSYSTEM"."SITE_PARAM_SPEC"

ALTER TABLE "MDSYSTEM"."SITE_PARAM_SPEC" 
	ADD CONSTRAINT "SQL020508213236300" FOREIGN KEY
		("SYS_ID")
	REFERENCES "MDSYSTEM"."SYSTEM"
		("SYS_ID")
	ON DELETE CASCADE
	ON UPDATE NO ACTION;

ALTER TABLE "MDSYSTEM"."SITE_PARAM_SPEC" 
	ADD CONSTRAINT "SQL020508213236320" FOREIGN KEY
		("TYPE_ID")
	REFERENCES "CHEM    "."SITE_PARAM_TYPE"
		("TYPE_ID")
	ON DELETE CASCADE
	ON UPDATE NO ACTION;


-- DDL Statements for foreign keys on Table "MDSYSTEM"."SITE_PARAM"

ALTER TABLE "MDSYSTEM"."SITE_PARAM" 
	ADD CONSTRAINT "SQL020508213236660" FOREIGN KEY
		("SYS_ID",
		 "PARAM_ID")
	REFERENCES "MDSYSTEM"."SITE_PARAM_SPEC"
		("SYS_ID",
		 "PARAM_ID")
	ON DELETE CASCADE
	ON UPDATE NO ACTION;

ALTER TABLE "MDSYSTEM"."SITE_PARAM" 
	ADD CONSTRAINT "SQL020508213236680" FOREIGN KEY
		("SYS_ID",
		 "SITE_ID")
	REFERENCES "MDSYSTEM"."SITE"
		("SYS_ID",
		 "SITE_ID")
	ON DELETE CASCADE
	ON UPDATE NO ACTION;


-- DDL Statements for foreign keys on Table "MDSYSTEM"."BOND"

ALTER TABLE "MDSYSTEM"."BOND" 
	ADD CONSTRAINT "SQL020508213237050" FOREIGN KEY
		("SYS_ID")
	REFERENCES "MDSYSTEM"."SYSTEM"
		("SYS_ID")
	ON DELETE CASCADE
	ON UPDATE NO ACTION;


-- DDL Statements for foreign keys on Table "MDSYSTEM"."GLOBAL_PARAMETER_TYPE"

ALTER TABLE "MDSYSTEM"."GLOBAL_PARAMETER_TYPE" 
	ADD CONSTRAINT "SQL020508213237380" FOREIGN KEY
		("SYS_ID")
	REFERENCES "MDSYSTEM"."SYSTEM"
		("SYS_ID")
	ON DELETE CASCADE
	ON UPDATE NO ACTION;


-- DDL Statements for foreign keys on Table "MDSYSTEM"."GLOBAL_PARAMETER"

ALTER TABLE "MDSYSTEM"."GLOBAL_PARAMETER" 
	ADD CONSTRAINT "SQL020508213237720" FOREIGN KEY
		("SYS_ID",
		 "PARAM_TYPE")
	REFERENCES "MDSYSTEM"."GLOBAL_PARAMETER_TYPE"
		("SYS_ID",
		 "PARAM_TYPE")
	ON DELETE CASCADE
	ON UPDATE NO ACTION;



COMMIT WORK;

CONNECT RESET;

TERMINATE;
