--****************************************************
--****************************************************
-- New MDSYSTEM Schema for use with In-memory DB
-- 06-07-2006
--****************************************************
--****************************************************
CONNECT TO MDTEST;

CREATE SCHEMA MDSYSTEM;

--****************************************************
--****************************************************
-- The following are original tables filled in by
-- xml2db2 
--****************************************************
--****************************************************

CREATE TABLE MDSYSTEM.System  (  
 sys_id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY ( START WITH 50000 ), 
 sys_desc VARCHAR(30) NOT NULL,  
 creator VARCHAR(40) NOT NULL, 
 created TIMESTAMP NOT NULL,
 sys_class VARCHAR(60) NOT NULL,
 PRIMARY KEY ( sys_id )) IN mdshort;

CREATE TABLE MDSYSTEM.chain  (
 sys_id            INT NOT NULL, 
 chain_id          INT NOT NULL, 
 chain_desc        VARCHAR(100),
 PRIMARY KEY ( sys_id, chain_id ),
 FOREIGN KEY ( sys_id) REFERENCES MDSYSTEM.System ON DELETE CASCADE) IN mdshort;

CREATE TABLE MDSYSTEM.chem_comp_instance  (
 sys_id            INT NOT NULL, 
 cc_instance_id    INT NOT NULL, 
 component_name    VARCHAR(100) NOT NULL, 
 PRIMARY KEY ( sys_id, cc_instance_id ),
 FOREIGN KEY ( sys_id) REFERENCES MDSYSTEM.System ON DELETE CASCADE,
 FOREIGN KEY ( component_name) REFERENCES CHEM.chemical_component ON DELETE CASCADE) IN mdshort;

CREATE TABLE MDSYSTEM.specific_molecule  (
 sys_id            INT NOT NULL, 
 mol_id            INT NOT NULL,
 molecule_name     VARCHAR(60) NOT NULL, 
 class             VARCHAR(60) NOT NULL, 
 generic_name      VARCHAR(60), 
 pdb_id            VARCHAR(60), 
 PRIMARY KEY ( sys_id, mol_id ),
 FOREIGN KEY ( sys_id) REFERENCES MDSYSTEM.System ON DELETE CASCADE,
 FOREIGN KEY ( class ) REFERENCES CHEM.molecule_type ON DELETE CASCADE) IN mdshort;

CREATE TABLE MDSYSTEM.molecule_instance  (
sys_id            INT NOT NULL, 
mol_instance_id   INT NOT NULL, 
mol_id            INT NOT NULL, 
PRIMARY KEY ( sys_id, mol_instance_id ),
FOREIGN KEY ( sys_id) REFERENCES MDSYSTEM.System ON DELETE CASCADE,
FOREIGN KEY ( sys_id, mol_id ) REFERENCES MDSYSTEM.specific_molecule ON DELETE CASCADE) IN mdshort;

CREATE TABLE MDSYSTEM.monomer_instance  (
 sys_id            INT NOT NULL, 
 chain_id          INT NOT NULL, 
 monomer_ordinal   INT NOT NULL, 
 cc_instance_id    INT NOT NULL, 
 PRIMARY KEY ( sys_id, chain_id, monomer_ordinal ),
 FOREIGN KEY ( sys_id ) REFERENCES MDSYSTEM.System ON DELETE CASCADE,
 FOREIGN KEY ( sys_id, chain_id ) REFERENCES MDSYSTEM.chain ON DELETE CASCADE,
 FOREIGN KEY ( sys_id, cc_instance_id ) REFERENCES MDSYSTEM.chem_comp_instance ON DELETE CASCADE) IN mdshort;

CREATE TABLE MDSYSTEM.ParamTupleList  (  
 sys_id INT NOT NULL, 
 param_tuple_list_id INT NOT NULL,
 param_tuple_desc VARCHAR(40),
 PRIMARY KEY ( sys_id, param_tuple_list_id ) , 
 FOREIGN KEY ( sys_id ) REFERENCES MDSYSTEM.System ON DELETE CASCADE) IN mdshort;

CREATE TABLE MDSYSTEM.ParamTupleSpec  ( 
 sys_id INT NOT NULL, 
 param_tuple_list_id INT NOT NULL, 
 param_id            INT NOT NULL, 
 param_type          INT, 
 param_name          VARCHAR(40), 
 PRIMARY KEY ( sys_id, param_tuple_list_id, param_id ), 
 FOREIGN KEY ( sys_id, param_tuple_list_id ) REFERENCES MDSYSTEM.ParamTupleList ON DELETE CASCADE) IN mdshort;

CREATE TABLE MDSYSTEM.ParamTuple  (
 sys_id INT NOT NULL, 
 param_tuple_list_id INT NOT NULL, 
 param_tuple_id      INT NOT NULL, 
 PRIMARY KEY ( sys_id, param_tuple_list_id, param_tuple_id ),
 FOREIGN KEY ( sys_id, param_tuple_list_id ) REFERENCES MDSYSTEM.ParamTupleList ON DELETE CASCADE) IN mdshort;

CREATE TABLE MDSYSTEM.ParamTupleData  ( 
 sys_id INT NOT NULL, 
 param_tuple_list_id INT NOT NULL, 
 param_tuple_id      INT NOT NULL,
 param_id            INT NOT NULL,
 param_value         VARCHAR(40), 
 PRIMARY KEY ( sys_id, param_tuple_list_id, param_tuple_id, param_id ), 
 FOREIGN KEY ( sys_id, param_tuple_list_id ) REFERENCES MDSYSTEM.ParamTupleList ON DELETE CASCADE) IN mdshort;

CREATE TABLE MDSYSTEM.SiteTupleList  ( 		      
 sys_id INT NOT NULL, 
 site_tuple_list_id INT NOT NULL, 
 site_tuple_desc VARCHAR(40),
 PRIMARY KEY (sys_id, site_tuple_list_id), 
 FOREIGN KEY ( sys_id ) REFERENCES MDSYSTEM.System ON DELETE CASCADE) IN mdshort;

CREATE TABLE MDSYSTEM.UDF_Invocation_Table  ( 
 sys_id INT NOT NULL, 		      
 udf_id VARCHAR(60) NOT NULL,
 site_tuple_list_id  INT NOT NULL,
 param_tuple_list_id INT,
 PRIMARY KEY (sys_id, udf_id, site_tuple_list_id),
 FOREIGN KEY ( sys_id, site_tuple_list_id ) REFERENCES MDSYSTEM.SiteTupleList  ON DELETE CASCADE,
 FOREIGN KEY ( sys_id, param_tuple_list_id )REFERENCES MDSYSTEM.ParamTupleList ON DELETE CASCADE) IN mdshort;
	 
CREATE TABLE MDSYSTEM.SiteTuple  (  
 sys_id INT NOT NULL, 
 site_tuple_list_id INT NOT NULL, 
 site_tuple_id      INT NOT NULL,
 PRIMARY KEY ( sys_id, site_tuple_list_id, site_tuple_id ),
 FOREIGN KEY ( sys_id, site_tuple_list_id ) REFERENCES MDSYSTEM.SiteTupleList ON DELETE CASCADE) IN mdshort;
	 
CREATE TABLE MDSYSTEM.Site  (
 sys_id INT NOT NULL, 
 site_id         INT NOT NULL, 
 cc_instance_id    INT,
 mol_instance_id INT,
 epsilon         VARCHAR(50),
 rmin            VARCHAR(50),
 epsilon14       VARCHAR(50),
 rmin14          VARCHAR(50),
 atomic_mass     VARCHAR(50),
 charge          VARCHAR(60),
 atom_tag        VARCHAR(60),
 component_name  VARCHAR(60),
 element_symbol  VARCHAR(10),
 PRIMARY KEY ( sys_id, site_id ),
 FOREIGN KEY ( sys_id ) REFERENCES MDSYSTEM.System ON DELETE CASCADE,
 FOREIGN KEY ( sys_id, mol_instance_id ) REFERENCES MDSYSTEM.molecule_instance ON DELETE CASCADE,
 FOREIGN KEY ( sys_id, cc_instance_id ) REFERENCES MDSYSTEM.chem_comp_instance ON DELETE CASCADE,
 FOREIGN KEY ( element_symbol ) REFERENCES CHEM.elements ON DELETE CASCADE,
 FOREIGN KEY ( component_name, atom_tag ) REFERENCES CHEM.atom_tag_table ON DELETE CASCADE) IN mdshort;
                      
CREATE TABLE MDSYSTEM.SiteTupleData  ( 
 sys_id INT NOT NULL, 
 site_tuple_list_id INT NOT NULL,
 site_tuple_id      INT NOT NULL,
 site_ordinal       INT NOT NULL,
 site_id            INT NOT NULL,
 PRIMARY KEY ( sys_id, site_tuple_list_id, site_tuple_id, site_ordinal ),
 FOREIGN KEY ( sys_id, site_tuple_list_id ) REFERENCES MDSYSTEM.SiteTupleList ON DELETE CASCADE,
 FOREIGN KEY ( sys_id, site_id )            REFERENCES MDSYSTEM.Site          ON DELETE CASCADE) IN mdshort;

CREATE TABLE MDSYSTEM.group  (
 sys_id INT NOT NULL,
 group_id INT NOT NULL,
 group_type VARCHAR(60) NOT NULL,
 PRIMARY KEY ( sys_id, group_id )) IN mdshort;

CREATE TABLE MDSYSTEM.group_site  (
 sys_id INT NOT NULL,
 group_id INT NOT NULL,
 site_id INT NOT NULL,
 PRIMARY KEY (sys_id, group_id, site_id),
 FOREIGN KEY ( sys_id, site_id )            REFERENCES MDSYSTEM.Site          ON DELETE CASCADE,
 FOREIGN KEY ( sys_id, group_id )           REFERENCES MDSYSTEM.group         ON DELETE CASCADE) IN mdshort;

CREATE TABLE MDSYSTEM.site_param_spec  (
 sys_id       INT NOT NULL,
 param_id     INT NOT NULL,
 type_id      INT NOT NULL,
 name      VARCHAR(60) NOT NULL,
 PRIMARY KEY (sys_id, param_id ),
 FOREIGN KEY ( sys_id )            REFERENCES MDSYSTEM.System          ON DELETE CASCADE,
 FOREIGN KEY ( type_id )           REFERENCES CHEM.site_param_type     ON DELETE CASCADE) IN mdshort;

CREATE TABLE MDSYSTEM.site_param  (
 sys_id    INT NOT NULL,
 site_id    INT NOT NULL,
 param_id    INT NOT NULL,
 value    VARCHAR(60) NOT NULL,
 PRIMARY KEY ( sys_id, site_id, param_id ),
 FOREIGN KEY ( sys_id, param_id ) REFERENCES MDSYSTEM.site_param_spec ON DELETE CASCADE,
 FOREIGN KEY ( sys_id, site_id ) REFERENCES MDSYSTEM.Site ON DELETE CASCADE) IN mdshort;


CREATE TABLE MDSYSTEM.Bond  ( 
 sys_id INT NOT NULL, 		      
 bond_id INT NOT NULL,
 site_id1 INT NOT NULL,
 site_id2 INT NOT NULL,
 bond_type INT,
 PRIMARY KEY ( sys_id, bond_id), 
 FOREIGN KEY ( sys_id ) REFERENCES MDSYSTEM.System ON DELETE CASCADE) IN mdshort;
	 
CREATE TABLE MDSYSTEM.Global_Parameter_Type  ( 
 sys_id INT NOT NULL, 
 param_type INT NOT NULL, 
 param_desc VARCHAR(60), 
 PRIMARY KEY ( sys_id, param_type ), 
 FOREIGN KEY ( sys_id ) REFERENCES MDSYSTEM.System ON DELETE CASCADE) IN mdshort;

CREATE TABLE MDSYSTEM.Global_Parameter  (  
 sys_id INT NOT NULL, 
 param_id VARCHAR(20) NOT NULL, 
 param_type INT NOT NULL, 
 symbolic_constant INT, 
 param_value VARCHAR(60),
 PRIMARY KEY ( sys_id, param_id  ), 
 FOREIGN KEY ( sys_id, param_type ) REFERENCES MDSYSTEM.Global_Parameter_Type ON DELETE CASCADE) IN mdshort;


--****************************************************
--****************************************************
-- The following are tables that will be filled 
-- in by the probspecTrans
--****************************************************
--****************************************************
CREATE TABLE MDSYSTEM.PST_Exp (
 exp_id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY ( START WITH 100 ), 
 exp_param_id INT NOT NULL,
 PRIMARY KEY (exp_id)
 ) in mdshort;

--****************************************************
CREATE TABLE MDSYSTEM.PST_Exp_Params (
 exp_param_id INT NOT NULL,
 paramname VARCHAR(60) NOT NULL,
 paramvalue VARCHAR(60) NOT NULL,
 PRIMARY KEY (exp_param_id, paramname, paramvalue)
 ) in mdshort;

--****************************************************
CREATE TABLE MDSYSTEM.PSTID_to_exp (
 pst_id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY ( START WITH 100 ), 
 sys_id INT NOT NULL,
 exp_id INT NOT NULL,
 PRIMARY KEY (pst_id),
 FOREIGN KEY (sys_id) REFERENCES MDSYSTEM.System ON DELETE NO ACTION,
 FOREIGN KEY (exp_id) REFERENCES MDSYSTEM.PST_Exp ON DELETE CASCADE
 ) in mdshort;

--****************************************************
CREATE TABLE MDSYSTEM.Online_Parameter (
 pst_id INT NOT NULL,
 fragid_exclusions_delta INT NOT NULL,
 water_method VARCHAR(60), 
 do_shake_water INT NOT NULL,
 do_shake_protein INT NOT NULL,
 time_conversion_factor DOUBLE NOT NULL,
 PRIMARY KEY (pst_id),
 FOREIGN KEY (pst_id) REFERENCES MDSYSTEM.PSTID_to_exp ON DELETE CASCADE
 ) in mdshort;


-- Rigid2Sites  &&
-- Rigid2_Params 
--****************************************************
CREATE TABLE MDSYSTEM.rigid2_sites (
 pst_id INT NOT NULL,
 heavy_site INT NOT NULL,
 hydrogen_site1 INT NOT NULL,
 hydrogen_site1_rEQ DOUBLE NOT NULL, 
 PRIMARY KEY (pst_id, heavy_site),
 FOREIGN KEY (pst_id) REFERENCES MDSYSTEM.PSTID_to_exp ON DELETE CASCADE
 ) in mdshort;

-- Rigid3Sites && 
-- Rigid3_Params 
--****************************************************
CREATE TABLE MDSYSTEM.rigid3_sites (
 pst_id INT NOT NULL,
 heavy_site INT NOT NULL,
 hydrogen_site1 INT NOT NULL,
 hydrogen_site1_rEQ DOUBLE NOT NULL, 
 hydrogen_site2 INT NOT NULL,
 hydrogen_site2_rEQ DOUBLE NOT NULL, 
 PRIMARY KEY (pst_id, heavy_site),
 FOREIGN KEY (pst_id) REFERENCES MDSYSTEM.PSTID_to_exp ON DELETE CASCADE
 ) in mdshort;

-- Rigid4Sites &&
-- Rigid4_Params
--****************************************************
CREATE TABLE MDSYSTEM.rigid4_sites (
 pst_id INT NOT NULL,
 heavy_site INT NOT NULL,
 hydrogen_site1 INT NOT NULL,
 hydrogen_site1_rEQ DOUBLE NOT NULL, 
 hydrogen_site2 INT NOT NULL,
 hydrogen_site2_rEQ DOUBLE NOT NULL, 
 hydrogen_site3 INT NOT NULL,
 hydrogen_site3_rEQ DOUBLE NOT NULL, 
 PRIMARY KEY (pst_id, heavy_site), 
 FOREIGN KEY (pst_id) REFERENCES MDSYSTEM.PSTID_to_exp ON DELETE CASCADE
 ) in mdshort;


-- ExternalToInternalSiteIDMap  &&
-- InternalToExternalSiteIDMap 
--****************************************************
CREATE TABLE MDSYSTEM.internal_external_siteids (
 pst_id INT NOT NULL,
 ext_site_id INT NOT NULL,
 int_site_id INT NOT NULL,
 PRIMARY KEY (pst_id, ext_site_id, int_site_id),
--  FOREIGN KEY (ext_site_id) REFERENCES MDSYSTEM.Site (site_id) ON DELETE CASCADE,
 FOREIGN KEY (pst_id) REFERENCES MDSYSTEM.PSTID_to_exp ON DELETE CASCADE
 ) in mdshort;

-- IrreduciblePartitionTypeList
--****************************************************
CREATE TABLE MDSYSTEM.fragment_type(
 pst_id INT NOT NULL,
 fragment_type_id INT NOT NULL,
 num_sites INT NOT NULL,
 molecule_type INT NOT NULL,
 tagatom_index INT NOT NULL,
 num_constraints INT NOT NULL,
 extent DOUBLE NOT NULL,
 PRIMARY KEY (pst_id, fragment_type_id),
 FOREIGN KEY (pst_id) REFERENCES MDSYSTEM.PSTID_to_exp ON DELETE CASCADE
 ) in mdshort;

-- IrreduciblePartitionIndexToTypeMap 
--****************************************************
CREATE TABLE MDSYSTEM.fragment_map(
 pst_id INT NOT NULL,
 start_site INT NOT NULL,
 fragment_type_id INT NOT NULL,
 molecule_id INT NOT NULL,
 frag_index_in_molecule INT NOT NULL,
 PRIMARY KEY (pst_id, start_site, fragment_type_id), 
 FOREIGN KEY (pst_id) REFERENCES MDSYSTEM.PSTID_to_exp ON DELETE CASCADE
 -- FOREIGN KEY (pst_id, fragment_type_id) REFERENCES MDSYSTEM.fragment_type(pst_id, fragment_type_id) ON DELETE CASCADE
 ) in mdshort;

-- SiteInformation &&
--****************************************************
CREATE TABLE MDSYSTEM.siteinfo (
 pst_id INT NOT NULL,
 info_id INT NOT NULL,  
 atomic_mass DOUBLE NOT NULL,  
 half_inverse_mass DOUBLE NOT NULL,
 charge DOUBLE NOT NULL,
 PRIMARY KEY (pst_id, info_id), 
 FOREIGN KEY (pst_id) REFERENCES MDSYSTEM.PSTID_to_exp ON DELETE CASCADE
 ) in mdshort;

-- SiteIDtoSiteTypeMap
--****************************************************
CREATE TABLE MDSYSTEM.site_to_siteinfo (
 pst_id INT NOT NULL,
 site_id INT NOT NULL,
 info_id INT NOT NULL,
 PRIMARY KEY (pst_id, site_id, info_id),
-- FOREIGN KEY (site_id) REFERENCES MDSYSTEM.internal_external_siteids (int_site_id) ON DELETE CASCADE,
-- FOREIGN KEY (info_id) REFERENCES MDSYSTEM.siteinfo (info_id) ON DELETE CASCADE, 
 FOREIGN KEY (pst_id) REFERENCES MDSYSTEM.PSTID_to_exp ON DELETE CASCADE
 ) in mdshort;

-- ExclusionList1_2_3_4 
--****************************************************
CREATE TABLE MDSYSTEM.exclusion_sites (
 pst_id INT NOT NULL,
 site1 INT NOT NULL,
 site2 INT NOT NULL,
 PRIMARY KEY (pst_id, site1, site2),
-- FOREIGN KEY (site1) REFERENCES MDSYSTEM.internal_external_siteids (int_site_id) ON DELETE CASCADE,
-- FOREIGN KEY (site2) REFERENCES MDSYSTEM.internal_external_siteids (int_site_id) ON DELETE CASCADE,
 FOREIGN KEY (pst_id) REFERENCES MDSYSTEM.PSTID_to_exp ON DELETE CASCADE
 ) in mdshort;

-- Pair14SiteList
-- Charge14PairTable
-- LJ14PairTable 
--****************************************************
CREATE TABLE MDSYSTEM.pair14_sites (
 pst_id INT NOT NULL,
 site1 INT NOT NULL,
 site2 INT NOT NULL,
 charge DOUBLE NOT NULL,
 lj_epsilon DOUBLE NOT NULL,
 lj_rmin DOUBLE NOT NULL,
 PRIMARY KEY (pst_id, site1, site2),
-- FOREIGN KEY (site1) REFERENCES MDSYSTEM.internal_external_siteids (int_site_id) ON DELETE CASCADE,
-- FOREIGN KEY (site2) REFERENCES MDSYSTEM.internal_external_siteids (int_site_id) ON DELETE CASCADE,
 FOREIGN KEY (pst_id) REFERENCES MDSYSTEM.PSTID_to_exp ON DELETE CASCADE
 ) in mdshort;

-- Water3sites 
--****************************************************
CREATE TABLE MDSYSTEM.water3_sites (
 pst_id INT NOT NULL,
 site_id1 INT NOT NULL,
 site_id2 INT NOT NULL,
 site_id3 INT NOT NULL,
 PRIMARY KEY (pst_id, site_id1, site_id2, site_id3),
-- FOREIGN KEY (site_id1) REFERENCES MDSYSTEM.internal_external_siteids (int_site_id) ON DELETE CASCADE,
-- FOREIGN KEY (site_id2) REFERENCES MDSYSTEM.internal_external_siteids (int_site_id) ON DELETE CASCADE,
-- FOREIGN KEY (site_id3) REFERENCES MDSYSTEM.internal_external_siteids (int_site_id) ON DELETE CASCADE,
 FOREIGN KEY (pst_id) REFERENCES MDSYSTEM.PSTID_to_exp ON DELETE CASCADE
 ) in mdshort;


--****************************************************
--****************************************************
-- The following are tables that are specific to
-- UDF BONDED FORCES
--****************************************************
--****************************************************

-- StdHarmonicBondForce_sitesSiteTupleList 
-- StdHarmonicBondForce_paramsParamTupleList 
--****************************************************
CREATE TABLE MDSYSTEM.StdHarmonicBondForce_TupleList (
 pst_id INT NOT NULL,
 tuple_id INT NOT NULL,
 site1 INT NOT NULL,
 site2 INT NOT NULL,
 k DOUBLE NOT NULL, 
 r0 DOUBLE NOT NULL, 
 PRIMARY KEY (pst_id, tuple_id),
 FOREIGN KEY (pst_id) REFERENCES MDSYSTEM.PSTID_to_exp ON DELETE CASCADE
-- FOREIGN KEY (site1) REFERENCES MDSYSTEM.internal_external_siteids (int_site_id) ON DELETE CASCADE,
-- FOREIGN KEY (site2) REFERENCES MDSYSTEM.internal_external_siteids (int_site_id) ON DELETE CASCADE
 ) in mdshort;

-- StdHarmonicAngleForce_sitesSiteTupleList 
-- StdHarmonicAngleForce_paramsParamTupleList 
--****************************************************
CREATE TABLE MDSYSTEM.StdHarmonicAngleForce_TupleList (
 pst_id INT NOT NULL,
 tuple_id INT NOT NULL,
 site1 INT NOT NULL,
 site2 INT NOT NULL,
 site3 INT NOT NULL,
 k DOUBLE NOT NULL,
 th0 DOUBLE NOT NULL,
 PRIMARY KEY (pst_id, tuple_id),
 FOREIGN KEY (pst_id) REFERENCES MDSYSTEM.PSTID_to_exp ON DELETE CASCADE
-- FOREIGN KEY (site1) REFERENCES MDSYSTEM.internal_external_siteids (int_site_id) ON DELETE CASCADE,
-- FOREIGN KEY (site2) REFERENCES MDSYSTEM.internal_external_siteids (int_site_id) ON DELETE CASCADE,
-- FOREIGN KEY (site3) REFERENCES MDSYSTEM.internal_external_siteids (int_site_id) ON DELETE CASCADE
 ) in mdshort;

-- UreyBradleyForce_sitesSiteTupleList
-- UreyBradleyForce_paramsParamTupleList
--****************************************************
CREATE TABLE MDSYSTEM.UreyBradleyForce_TupleList (
 pst_id INT NOT NULL,
 tuple_id INT NOT NULL,
 site1 INT NOT NULL,
 site2 INT NOT NULL,
 k DOUBLE NOT NULL,
 s0 DOUBLE NOT NULL,
 PRIMARY KEY (pst_id, tuple_id),
 FOREIGN KEY (pst_id) REFERENCES MDSYSTEM.PSTID_to_exp ON DELETE CASCADE
-- FOREIGN KEY (site1) REFERENCES MDSYSTEM.internal_external_siteids (int_site_id) ON DELETE CASCADE,
-- FOREIGN KEY (site2) REFERENCES MDSYSTEM.internal_external_siteids (int_site_id) ON DELETE CASCADE
 ) in mdshort;

-- SwopeTorsionForce_sitesSiteTupleList
-- SwopeTorsionForce_paramsParamTupleList
--****************************************************
CREATE TABLE MDSYSTEM.SwopeTorsionForce_TupleList (
 pst_id INT NOT NULL,
 tuple_id INT NOT NULL,
 site1 INT NOT NULL,
 site2 INT NOT NULL,
 site3 INT NOT NULL,
 site4 INT NOT NULL,
 cosDelta DOUBLE NOT NULL,
 k DOUBLE NOT NULL,
 sinDelta DOUBLE NOT NULL,
 n INT NOT NULL,
 PRIMARY KEY (pst_id, tuple_id),
 FOREIGN KEY (pst_id) REFERENCES MDSYSTEM.PSTID_to_exp ON DELETE CASCADE
-- FOREIGN KEY (site1) REFERENCES MDSYSTEM.internal_external_siteids (int_site_id) ON DELETE CASCADE,
-- FOREIGN KEY (site2) REFERENCES MDSYSTEM.internal_external_siteids (int_site_id) ON DELETE CASCADE,
-- FOREIGN KEY (site3) REFERENCES MDSYSTEM.internal_external_siteids (int_site_id) ON DELETE CASCADE,
-- FOREIGN KEY (site4) REFERENCES MDSYSTEM.internal_external_siteids (int_site_id) ON DELETE CASCADE
 ) in mdshort;

-- ImproperDihedralForce_sitesSiteTupleList
-- ImproperDihedralForce_paramsParamTupleList
--****************************************************
CREATE TABLE MDSYSTEM.ImproperDihedralForce_TupleList (
 pst_id INT NOT NULL,
 tuple_id INT NOT NULL,
 site1 INT NOT NULL,
 site2 INT NOT NULL,
 site3 INT NOT NULL,
 site4 INT NOT NULL,
 k DOUBLE NOT NULL,
 psi0 DOUBLE NOT NULL,
 PRIMARY KEY (pst_id, tuple_id),
 FOREIGN KEY (pst_id) REFERENCES MDSYSTEM.PSTID_to_exp ON DELETE CASCADE
-- FOREIGN KEY (site1) REFERENCES MDSYSTEM.internal_external_siteids (int_site_id) ON DELETE CASCADE,
-- FOREIGN KEY (site2) REFERENCES MDSYSTEM.internal_external_siteids (int_site_id) ON DELETE CASCADE,
-- FOREIGN KEY (site3) REFERENCES MDSYSTEM.internal_external_siteids (int_site_id) ON DELETE CASCADE,
-- FOREIGN KEY (site4) REFERENCES MDSYSTEM.internal_external_siteids (int_site_id) ON DELETE CASCADE
 ) in mdshort;

-- OPLSTorsionForce_sitesSiteTupleList
-- OPLSTorsionForce_paramsParamTupleList
--****************************************************
CREATE TABLE MDSYSTEM.OPLSTorsionForce_TupleList (
 pst_id INT NOT NULL,
 tuple_id INT NOT NULL,
 site1 INT NOT NULL,
 site2 INT NOT NULL,
 site3 INT NOT NULL,
 site4 INT NOT NULL,
 cosDelta DOUBLE NOT NULL,
 k DOUBLE NOT NULL,
 sinDelta DOUBLE NOT NULL,
 n INT NOT NULL,
 PRIMARY KEY (pst_id, tuple_id),
 FOREIGN KEY (pst_id) REFERENCES MDSYSTEM.PSTID_to_exp ON DELETE CASCADE
-- FOREIGN KEY (site1) REFERENCES MDSYSTEM.internal_external_siteids (int_site_id) ON DELETE CASCADE,
-- FOREIGN KEY (site2) REFERENCES MDSYSTEM.internal_external_siteids (int_site_id) ON DELETE CASCADE,
-- FOREIGN KEY (site3) REFERENCES MDSYSTEM.internal_external_siteids (int_site_id) ON DELETE CASCADE,
-- FOREIGN KEY (site4) REFERENCES MDSYSTEM.internal_external_siteids (int_site_id) ON DELETE CASCADE
 ) in mdshort;

-- OPLSImproperForce_sitesSiteTupleList
-- OPLSImproperForce_paramsParamTupleList
--****************************************************
CREATE TABLE MDSYSTEM.OPLSImproperForce_TupleList (
 pst_id INT NOT NULL,
 tuple_id INT NOT NULL,
 site1 INT NOT NULL,
 site2 INT NOT NULL,
 site3 INT NOT NULL,
 site4 INT NOT NULL,
 cosDelta DOUBLE NOT NULL,
 k DOUBLE NOT NULL,
 sinDelta DOUBLE NOT NULL,
 n INT NOT NULL,
 PRIMARY KEY (pst_id, tuple_id),
 FOREIGN KEY (pst_id) REFERENCES MDSYSTEM.PSTID_to_exp ON DELETE CASCADE
-- FOREIGN KEY (site1) REFERENCES MDSYSTEM.internal_external_siteids (int_site_id) ON DELETE CASCADE,
-- FOREIGN KEY (site2) REFERENCES MDSYSTEM.internal_external_siteids (int_site_id) ON DELETE CASCADE,
-- FOREIGN KEY (site3) REFERENCES MDSYSTEM.internal_external_siteids (int_site_id) ON DELETE CASCADE,
-- FOREIGN KEY (site4) REFERENCES MDSYSTEM.internal_external_siteids (int_site_id) ON DELETE CASCADE
 ) in mdshort;



--****************************************************
--****************************************************
-- The following are tables that are specific to
-- UDF NSQ-NON-BONDED FORCES
--****************************************************
--****************************************************

-- ChargeNsqParams 
-- LJNsqParams 
--****************************************************
CREATE TABLE MDSYSTEM.nsq_siteinfo (
 pst_id INT NOT NULL,
 info_id INT NOT NULL,
 charge DOUBLE NOT NULL,
 lj_epsilon DOUBLE NOT NULL,
 lj_rmin DOUBLE NOT NULL,
 PRIMARY KEY (pst_id, info_id),
 FOREIGN KEY (pst_id) REFERENCES MDSYSTEM.PSTID_to_exp ON DELETE CASCADE
 ) in mdshort;

-- NsqSiteIDtoSiteTypeMap 
--****************************************************
CREATE TABLE MDSYSTEM.nsq_site_to_nsq_siteinfo (
 pst_id INT NOT NULL,
 site_id INT NOT NULL,
 info_id INT NOT NULL,
 PRIMARY KEY (pst_id, site_id),
-- FOREIGN KEY (site_id) REFERENCES MDSYSTEM.internal_external_siteids (int_site_id) ON DELETE CASCADE,
 FOREIGN KEY (pst_id, info_id) REFERENCES MDSYSTEM.nsq_siteinfo (pst_id, info_id) ON DELETE CASCADE, 
 FOREIGN KEY (pst_id) REFERENCES MDSYSTEM.PSTID_to_exp ON DELETE CASCADE
 ) in mdshort;


COMMIT WORK;

CONNECT RESET;

TERMNINATE;







