# Source reship list
VPATH = ..
ILIST = \
  makefile.aix \
  monitor.hpp \
  Makefile.ode
makefile.aix_IDIR = $(BG_SRC)/bgfe/pk/util_test/include/
monitor.hpp_IDIR = $(BG_SRC)/bgfe/pk/util_test/include/
Makefile.ode_IDIR = $(BG_SRC)/bgfe/pk/util_test/include/source_ship/
.include <$(RULES_MK)>
