# Source reship list
VPATH = ..
ILIST = \
  README \
  crd2dvs.pl \
  top2xml.pl \
  Makefile.ode
README_IDIR = $(BG_SRC)/BlueMatter/xmlgen/amber6/
crd2dvs.pl_IDIR = $(BG_SRC)/BlueMatter/xmlgen/amber6/
top2xml.pl_IDIR = $(BG_SRC)/BlueMatter/xmlgen/amber6/
Makefile.ode_IDIR = $(BG_SRC)/BlueMatter/xmlgen/amber6/source_ship/
.include <$(RULES_MK)>
