# Source reship list
VPATH = ..
ILIST = \
  globject.hpp \
  makefile.aix \
  Makefile.ode
globject.hpp_IDIR = $(BG_SRC)/bgfe/pk/globject/include/
makefile.aix_IDIR = $(BG_SRC)/bgfe/pk/globject/include/
Makefile.ode_IDIR = $(BG_SRC)/bgfe/pk/globject/include/source_ship/
.include <$(RULES_MK)>
