EXPINC_SUBDIRS = \
 include \

OBJECTS_SUBDIRS = \
 src \

EXPLIB_SUBDIRS = $(OBJECTS_SUBDIRS)
SUBDIRS = $(EXPINC_SUBDIRS) $(OBJECTS_SUBDIRS)

.if defined(RESHIP_SOURCE)
ILIST += Makefile.ode
Makefile.ode_IDIR = $(BG_SRC)/./bgfe/pk/platform/
.endif # RESHIP_SOURCE
.include <$(RULES_MK)>
