# Source reship list
VPATH = ..
ILIST = \
  globject.cpp \
  makefile.aix \
  Makefile.ode
globject.cpp_IDIR = $(BG_SRC)/bgfe/pk/globject/src/
makefile.aix_IDIR = $(BG_SRC)/bgfe/pk/globject/src/
Makefile.ode_IDIR = $(BG_SRC)/bgfe/pk/globject/src/source_ship/
.include <$(RULES_MK)>
